BIP-44 33. AddressPool - core types and algorithm.
input-output-hk/cardano-wallet-legacy pull request #118
Opened 2018-11-27 17:25 UTC by denisshevchenko

# Linked Issue

<Put here a reference to the issue this PR relates to and which requirements it tackles>

<p align="right">#33</p>

# Overview

<Detail in a few bullet points the work accomplished in this PR>

1. - [x] `AddressPool` module is created.
2. - [x] It supports EOS-wallets only for now.

# Comments

<Additional comments or screenshots to attach if any>

¯\\\_(ツ)\_/¯

# Checklist

- [x] I've kept this PR simple, on-the-spot, free of cosmetic changes.
- [x] I have reviewed my commit messages and history.
- [x] I've assigned a reviewer.
- [x] I acknowledge my changes may require an update in the wiki.
- [x] I have added a reference to this PR to the corresponding issue.

---

- [x] I've checked the checklist

2018-11-28 09:29 UTC, KtorZ requested changes

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    , AddressPool (..)
_must fix_

Let's not expose the internals of `AdressPool` to make the implementation more robust.

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +getRawAddressPoolGap (AddressPoolGap gap) = fromIntegral gap
_must fix_

What about deriving the `Integral` type-class instead of the `AddressPoolGap` ?

```hs
{-# GeneralizedNewtypeDeriving #-}
{-# DerivingStrategies #-}

 newtype AddressPoolGap = AddressPoolGap { getAddressPoolGap :: Word8 }
     deriving (Eq, Generic, Ord, Show)
     deriving newtype (Integral)
```

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    nextAddressRange = newAddressRange (getRawAddressPoolGap gap) (increaseAddressIx lastIx)
_must fix_

`getRawAddressPoolGap` -> cf below

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +import           Cardano.Wallet.Kernel.DB.HdWallet (HdAddressIx (..))
_may fix_

Not sure why do we need this `HdAddressIx` at this stage :thinking: ? Can't we just go for an `Int` or something similar?

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +type NewAddress address = HdAddressIx -> address
_may fix_

Let's avoid the type alias completely. It doesn't buy us much in terms of readability and mask the actual type. The "desugarized" version looks clearer to me:

```hs
initAddressPool
    :: (Eq account, Ord address)
    => AddressPoolGap
    -> (HdAddressIx -> address)
    -> [account]
    -> AddressPool account address
initAddressPool gap newAddress accountPublicKeys
```

What do you think?

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -- address discovered would immediately trigger a range extension)
_may fix_

Well... yes? And isn't this the whole point of the algorithm :sweat_smile: ? I mean, this isn't tackling any _real_ issue, is it ?

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +newAddressRange range (HdAddressIx fromIx) newAddress =
_must fix_

`range :: Word32` really is `gap :: AddressPoolGap` here, right ?

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +                               (_addrPoolAccounts pool)
_must fix_

Let's just pass in the `pool` to the underlying function. It uses everything anyway ...

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    Nothing                 -> (pool, Nothing)
_must fix_

So, here we discard the `amendment` which I guess should have been applied by this `addressInPool` top-level function. Though, the indirection seems unnecessary here. Instead, we could apply the amendment directly to the pool and return the new pool as part of `addressInAllPools`. 
Doing so, `addressInAllPools` just becomes `addressInPool` ... 

Beside, I am not sure we need the `Amendment` abstraction at all? What about replacing these with corresponding three function to perform pool amendment and call them directly?

2018-11-28 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +addressInAllPools gap newAddress (p:ps) addr =
_must fix_

cf above comment, there's no reason for this indirection, this _is_ `addressInPool`

2018-11-28 10:37 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +type NewAddress address = HdAddressIx -> address
Hm... I don't have a strong opinion about type aliases. I mean, I don't think they are evil, but don't think it's really useful.

2018-11-28 10:38 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -- address discovered would immediately trigger a range extension)
It was old comment from @uroboros, I just kept it. :-)

2018-11-28 11:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -- address discovered would immediately trigger a range extension)
Yes, but the comment justifies to the binding below; which I think is wrong :) (not the comment, the justification and the binding)

2018-11-28 16:50 UTC, KtorZ submitted a review, later dismissed

2018-11-28 16:50 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    toIx = fromIx + (fromIntegral range) - 1
_must fix_

polishing: let's rename `range` to `gap` here

2018-11-28 16:50 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +        addressInGap lastIx foundIx = lastIx - foundIx <= fromIntegral gap
_must fix_ 

:disappointed: Awe... we went from a set of composable functions with type signatures to one gigantic function doing all the work. 
The logic and structure was quite fine before; the issue was the indirection through the "Amendment" which could be applied inline but that's pretty much it.

2018-11-28 16:50 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    defaultRange = gap * 2
_must fix_

This should just be `gap`

2018-11-28 21:48 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -> (AddressPoolPerAccount account address, Maybe (account, Word))
_must fix_

Almost there: 

- `accPool` is in `pool`
- let's return (AddressPool account address, Maybe (account, Word))

2018-11-28 21:48 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +            ( probablyAmendedAccPool
_may fix_

What about.. `pool'` :smile: ? `probablyAmendedAccPool` seems like overkill to me.

2018-11-28 21:48 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -> AddressPoolPerAccount account address
_must fix_

cf above comment

2018-11-28 21:48 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -> AddressPoolPerAccount account address
_must fix_

cf above comment

2018-11-29 08:27 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -> (AddressPoolPerAccount account address, Maybe (account, Word))
Yes, but we use this function to map over all `accPool`s.

2018-11-29 08:30 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    -> (AddressPoolPerAccount account address, Maybe (account, Word))
So what 😅?

2018-11-29 15:42 UTC, KtorZ commented
@denisshevchenko @uroboros 

I made some refactor on top of both of your work... I believe you guys wanted to go for the moon right away whereas it was in reality much simpler.

Cf: https://github.com/input-output-hk/cardano-wallet/pull/118/files#diff-47b287c925a0cae5fea93e9da0fb9e40R92

The module was really not more than this. Tested roughly through this dummy example:

```hs
main :: IO ()
main = do
    let (Right gap) = mkAddressPoolGap 10
    pure (initAddressPool gap (\ix -> fromJust $ Map.lookup ix pokemons))
        >>= prettyPrint "-" . (Nothing,)
	    -- AddressPool (gap: 10) (total: 10)
        --   [ blastoise:9, bulbasaur:1, charizard:6, charmander:4, charmeleon:5
        --   , ivysaur:2, mew:-0, squirtle:7, venusaur:3, wartortle:8
        --   ]

        >>= prettyPrint "charizard (ix=06)" . lookupAddressPool "charizard"
	    -- Found: Just ("charizard",6)
	    -- AddressPool (gap: 10) (total: 17)
        --   [ beedrill:15, blastoise:9, bulbasaur:1, butterfree:12, caterpie:10
        --   , charizard:6, charmander:4, charmeleon:5, ivysaur:2, kakuna:14
        --   , metapod:11, mew:-0, pidgey:16, squirtle:7, venusaur:3, wartortle:8
        --   , weedle:13
        --   ]

        >>= prettyPrint "bulbasaur (ix=01)" . lookupAddressPool "bulbasaur"
	    -- Found: Just ("bulbasaur",1)
	    -- AddressPool (gap: 10) (total: 17) 
        --   [ beedrill:15, blastoise:9, bulbasaur:1, butterfree:12, caterpie:10
        --   , charizard:6, charmander:4, charmeleon:5, ivysaur:2, kakuna:14
        --   , metapod:11, mew:-0, pidgey:16, squirtle:7, venusaur:3, wartortle:8
        --   , weedle:13
        --   ]

        >>= prettyPrint "pikachu   (ix=25)" . lookupAddressPool "pikachu"
	    -- Found: Nothing
	    -- AddressPool (gap: 10) (total: 17) 
        --   [ beedrill:15, blastoise:9, bulbasaur:1, butterfree:12, caterpie:10
        --   , charizard:6, charmander:4, charmeleon:5, ivysaur:2, kakuna:14
        --   , metapod:11, mew:-0, pidgey:16, squirtle:7, venusaur:3, wartortle:8
        --   , weedle:13
        --   ]

        >>= prettyPrint "pidgey    (ix=16)" . lookupAddressPool "pidgey"
        -- Found: Just ("pidgey",16)
	    -- AddressPool (gap: 10) (total: 27) 
        --   [ arbok:24, beedrill:15, blastoise:9, bulbasaur:1, butterfree:12
        --   , caterpie:10, charizard:6, charmander:4, charmeleon:5, ekans:23
        --   , fearow:22, ivysaur:2, kakuna:14, metapod:11, mew:-0, pidgeot:18
        --   , pidgeotto:17, pidgey:16, pikachu:25, raichu:26, raticate:20
        --   , rattata:19, spearow:21, squirtle:7, venusaur:3, wartortle:8
        --   , weedle:13
        --   ]

        >>= \_ -> return ()
  where
    prettyPrint
        :: Text
        -> (Maybe (String, Word), AddressPool String)
        -> IO (AddressPool String)
    prettyPrint key (addr, pool) =
        pure pool <* putStrLn ("Lookup " <> key
            <> "\n\tFound: " <> show addr
            <> "\n\t" <> sformat build pool)

pokemons :: Map Word String
pokemons = Map.fromList
    [ (0,"mew")
    , (1,"bulbasaur")
    , (2,"ivysaur")
    , (3,"venusaur")
    , (4,"charmander")
    , (5,"charmeleon")
    , (6,"charizard")
    , (7,"squirtle")
    , (8,"wartortle")
    , (9,"blastoise")
    , (10,"caterpie")
    , (11,"metapod")
    , (12,"butterfree")
    , (13,"weedle")
    , (14,"kakuna")
    , (15,"beedrill")
    , (16,"pidgey")
    , (17,"pidgeotto")
    , (18,"pidgeot")
    , (19,"rattata")
    , (20,"raticate")
    , (21,"spearow")
    , (22,"fearow")
    , (23,"ekans")
    , (24,"arbok")
    , (25,"pikachu")
    , (26,"raichu")
    , (27,"sandshrew")
    , (28,"sandslash")
    , (29,"nidoran-f")
    , (30,"nidorina")
    ]
```

2018-11-29 17:43 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +initAddressPool defaultGap newAddress = AddressPool
Why do we call it `defaultGap` here? I thought that _default_ gap is a value we took from BIP-44 spec..

2018-11-29 17:45 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    | isOnEdge  = pool & addresses %~ (next <>)
Lens magic... :-D

2018-11-29 17:51 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    if predicate then action else error msg
`error`?? Hm... If it's possible that `toIx <= fromIx`, maybe `initAddressPool` should return something like `Either InitAddressPoolError (AddressPool address)`?

2018-11-29 17:53 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +initAddressPool defaultGap newAddress = AddressPool
It's called `defaultGap` because `gap` conflicts with the lens's name and I couldn't come up with a better name :no_mouth: 

Suggestions :upside_down_face: ?

2018-11-29 17:57 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    | isOnEdge  = pool & addresses %~ (next <>)
Haha, to be honest, I always go away with 3 lens operators:

- `(^.)` which works as a simple getter, roughly equivalent to `s -> a` 
- `(.~)` which works as a simple setter, roughly equivalent to `s -> a -> s` 
- `(%~)` which words as a simple modifier, roughly equivalent to `s -> (a -> a) -> s`

So, the last one allows you to set a new value based on the previous one. Here, we just go for `next <>`, to append the new map :)

2018-11-29 18:00 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    if predicate then action else error msg
`error` because, well, in theory, this cannot happen through normal usage of the function. If it happens, it means we fucked up the implementation, and that's not something we want users of the function (might it be us) to handle.
That's clearly an invariant violation. 

It was there before, when doing `NE.fromList` ... I am just making it really clear here from the code. And that's always better than `*** Exception: Prelude.head: empty list` you'd get otherwise. Here, at least, you get a proper invariant message to help debugging.

2018-11-29 18:03 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +initAddressPool defaultGap newAddress = AddressPool
`aGap`, `gap_`, `ourGap`, but not `defaultGap` please, it's confused IMHO.

2018-11-29 18:04 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    if predicate then action else error msg
> If it happens, it means we fucked up the implementation...

Ok, agree. :-)

2018-11-29 18:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +initAddressPool defaultGap newAddress = AddressPool
Done -> `gap_`

2018-11-29 18:28 UTC, KtorZ approved these changes
Reviewed :+1:

2018-11-29 18:35 UTC, merged