Integration Test Framework - Part 1
input-output-hk/cardano-wallet-legacy pull request #126
Opened 2018-11-30 16:04 UTC by KtorZ

# Linked Issue

<Put here a reference to the issue this PR relates to and which requirements it tackles>

<p align="right">#117</p>

# Overview

<Detail in a few bullet points the work accomplished in this PR>

1. - [ ] Define a framework baseline for integration tests
2. - [ ] Translate (almost) each existing integration tests to this new framework (are missing: the two tests related to asset-locked wallets, will do later). 
3. - [ ] Remove existing integration tests

# Comments

<Additional comments or screenshots to attach if any>

This is... a lot, but most of the work happens only in a few place:

- `Test.Integration.Framework.Scenario`: defines a `Scenario` monad within which each test is running. This is basically a state monad, that is used as a reader for most test action except "setup" (cf remark below). There's a bit of plumbing here to make sure that things are hooked up into `HSpec` framework in such way that the footprint is rather small. In the end, we can leverage all of the `HSpec` tooling around this.

- `Test.Integration.Framework.DSL`: defines a DSL that is used to define integration tests. Ideally, we would use only combinators from that module to write test. This is to favor a very consistent, succinct and readable format for writing integration tests (remember that this may be read and analyzed by QA on the long run, and we can even imagine some of them being written by QA as well). So in a way, if I am only interested in writing and reading integration tests, I should only be looking at the DSL top-level interface. Note that, there's quite some boilerplate in that file and I hope that in the long run, we may be able to replace most of it with a fresh version of our API types :) 

Important remark: I haven't ran any of this yet :upside_down_face:  ... Actually, there's some work to be done with the cluster to decouple it from the wallet (hopefully next week). Before that, it should be possible to create a WalletClient by hand and test everything out, we will simply not get coverage out of that and need to start tests and server separately. That's probably what I'll do first to test that swiftly. 

Finally, there's also some "bootstrapping" necessary here. Ideally, we would like to reset the state of the blockchain between each test run. That's really not practical and would make all tests very long to run. Instead, I have been following a slightly different approach: some tests can be ran without any coins, some (most of them) needs a few funds. We have a few "genesis" wallets at our disposal with millions of ADA one each. So, before starting any test, we actually divide this amount in `k` and provide each test with some ADA they can use for testing. The amount of ADA available depends on the amount of tests, but we should have enough ADA to run A LOT of them without missing any. 

# Checklist

- [ ] ~~I've kept this PR simple, on-the-spot, free of cosmetic changes.~~ Sorry :( 
- [x] I have reviewed my commit messages and history.
- [x] I've assigned a reviewer.
- [x] I acknowledge my changes may require an update in the wiki.
- [ ] I have added a reference to this PR to the corresponding issue.

---

- [x] I've checked the checklist

2018-11-30 16:07 UTC, KtorZ commented on test/integration/Test/Integration/APISanityChecks.hs
> +module Test.Integration.APISanityChecks
Pretty much copy-pasted from before. I only remove one check saying that all `DELETE` should be `204` (that's actually not true since some of our DELETE are `404`) and also increased the number of randomly generated transactions from 100 to 1000... 
I'd actually like to see what kind of requests are generated and if this whole thing actually does check something :thinking:  ... but for now, I just kept it.

2018-11-30 16:08 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Orphan.hs
> +    \ literal notation when writing integration tests scenarios."
Perhaps a `newtype` here.. I don't know

2018-11-30 16:09 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Request.hs
> +        -> m (Either ClientError (Response originalResponse))
I wonder if we couldn't modify the client to actually do that for us directly. The `jsend` wrapper is pretty much useless (except for the metadata maybe .. and even... ).

2018-11-30 16:12 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Scenario.hs
> +            putMVar mvar s'
So, here's the trick. We save the context from a scenario to another. The only thing that actually gets modified in the context are the faucet wallets. So here, we're basically keeping track of a counter, and it gets incremented between each test, like a good global variable. In theory, the tests themselves only need this to be a `MonadReader`.

2018-11-30 16:14 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Scenario.hs
> +runWithContext :: forall ctx. ctx -> SpecM ctx () -> Spec
So, HSpec can't run anything else than `Spec = SpecM (ActionWith ()) ()`; So this makes the transformation, provided a context.

2018-11-30 16:15 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            ]
And finally, some test scenario ! Notice they're all divided in 3 "paragraphs"

- Setup
- Action
- Expectations

The DSL makes is possible to almost read it like a sentence and combinators are re-usable between types to make things quite smooth.

2018-11-30 21:36 UTC, parsonsmatt submitted a review, later dismissed
These look great!

I would suggest using `HasType` rather than `HasField`, as it's a bit more general and a bit less fragile (eg changing a field name breaks `HasField` instances, and `HasType` is capable of digging into datatypes recursively to find a value).

2018-11-30 21:36 UTC, parsonsmatt commented on .stylish-haskell.yaml
> +  - DerivingStrategies
:joy:

2018-11-30 21:36 UTC, parsonsmatt commented on cardano-wallet.cabal
> -
:joy:

2018-11-30 21:36 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    :: (HasCallStack, Example (Scenario Context IO ()))
This constraint is dodgy. It is fully saturated, which means we expect some orphan instance to come by and satisfy it.

2018-11-30 21:36 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +import           Data.Generics.Product.Fields (HasField, field)
`generic-lens` <3 <3 <3

2018-11-30 21:36 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Orphan.hs
> +    \ literal notation when writing integration tests scenarios."
Why not just use a constructor? or a function? I'm not a fan of abusing `Num` for things like this, where *all* the methods are errors.

2018-11-30 21:36 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Scenario.hs
> +newtype Scenario s m a = Scenario (StateT s m a)
Beware -- `StateT` is single-threaded state, and this is usually not what folks want in th epresence of concurrency and exceptions.

2018-12-01 09:53 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Orphan.hs
> +    \ literal notation when writing integration tests scenarios."
Well, the focus is really on keeping the end-to-end scenarios simple (read as: for non-haskellers), so I am really trying to remove as much noise as possible.

2018-12-01 09:55 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    :: (HasCallStack, Example (Scenario Context IO ()))
Hmmm... right my bad, there's no need for a constraint actually. I just "copy/pasted" the signature of `it` without much thinking :man_shrugging:

2018-12-01 09:59 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Scenario.hs
> +newtype Scenario s m a = Scenario (StateT s m a)
Indeed, though here all the tests are running sequentially in a single-thread. We _could_ possibly run them in parallel I believe, and it shouldn't matter much because we don't do any concurrent business inside the `StateT`.
It'd would require to adjust where the `MVar` is manipulated however; but that's clearly not the intent anyway or at least, not in the first iteration :)

2018-12-03 17:05 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Orphan.hs
> +    \ literal notation when writing integration tests scenarios."
Confusion can come from many things -- excess polymorphism can certainly do it. `coins 0` is slightly noisier than `0` but is more explicit and monomorphic, which should provide for better error messages too.

2018-12-03 17:08 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Scenario.hs
> +runWithContext :: forall ctx. ctx -> SpecM ctx () -> Spec
This can also be defined as `runWithContext ctx = beforeAll (pure ctx)`

2018-12-04 17:13 UTC, parsonsmatt requested changes

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +scenario title spec = it title (successfulRequest Client.resetWalletState >> spec)
so this is basically `before_ (successfulRequest Client.resetWalletState) $ it title spec` and `before` basically applies to every item in an `hspec` test.

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +scenario title spec = it title (successfulRequest Client.resetWalletState >> spec)
So, another way to structure this would be:

```haskell
before (successfulRequest Client.resetWalletState) $ do
  it "does a thing" $ do
     ...

  it "does another thing" $ do
    blaaah
```

Not necessary, just a tip on hspec :)

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    (.~) typed (Just i)
I'd rather see the operator used infix or the named function used:

```suggestion
    typed .~ Just i
```

```suggestion
    set typed (Just i)
```

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    (.~) typed
likewise, this is

```suggestion
    set typed
```

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    (%~) typed (PaymentDistribution (V1 a) (V1 c) :)
```suggestion
    over typed (PaymentDistribution (V1 a) (V1 c) :)
```

or 

```suggestion
    typed %~ (PaymentDistribution (V1 a) (V1 c) :)
```

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    (.~) typed
note that `set typed` exists in the class as `setType`: http://hackage.haskell.org/package/generic-lens-1.1.0.0/docs/Data-Generics-Product-Typed.html#v:setTyped

Therefore, many of these definitions can simply be:

```haskell
walletOperation :: HasType WalletOperation s => WalletOperation -> s -> s
walletOperation = setTyped
```

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    :: ( MonadIO m, MonadFail m, Show a, Eq a, lens ~ ((a -> Const a a) -> s -> Const a s))
Why not use the type alias, `Getter s a`?

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    expectFieldEqual ($)
This threw me for a loop for a bit -- I'd expect `expectFieldEqual id` to be a bit clearer.

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +notInitialized proxy =
I'm feeling *really* iffy on this. It's used in 12 other places, and basically means that we're throwing away the "If it type checks, it works!" feature for Haskell for *anything* that calls one of the functions. I don't like that.

It seems that we're using this for almost all of the fields in all of the use sites. We only provide a few default values. It would be more direct to have the caller pass in the entire data structure -- right now, uses are using lensy setters (eg `walletId wallet :: HasType WalletId s => s -> s`). A more direct construction would use:

```haskell
getAccountBalance :: AccountBalance -> ...

getAccountBalance AccountBalance { _walletId = walId wallet } 
```

Then, with strict fields, the user gets an error if they forget to set something.

If we want to allow defaults, then we can use functions of the form `(defParam -> defParam2 -> Thing)`, like:

```haskell
getAccountBalance (\defWalletId defOtherThing -> AccountBalance myThing defWalletId defOtherThing) ...
```

The least boilerplate-y thing might just be to take the required things as parameters directly.

I'm happy to help with hashing out an alternative to this.

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    either (error "fromRight: can't take right side of 'Left' value") id
I would really prefer to see this as a `MonadFail` rather than a pure exception. There's only one use, and it's to set a backup phrase -- we *really* shouldn't be throwing away Haskell's type safety just because we're writing tests.

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Request.hs
> +type HasHttpClient ctx = HasField "_client" ctx ctx (WalletClient IO) (WalletClient IO)
note that `HasType (WalletClient IO) ctx` also works here and is more general :)

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Request.hs
> +type HasHttpClient ctx = HasField "_client" ctx ctx (WalletClient IO) (WalletClient IO)
I'm of the opinion that a class like this could also be a class alias:

```haskell
class (HasType (WalletClient IO) ctx) => HasHttpClient ctx where
    httpClient :: Lens' ctx (WalletClient IO)
    httpClient = typed @(WalletClient IO)

instance (HasType (WalletClient IO) ctx) => HasHttpClient ctx
```

This allows someone to import `HasHttpClient(..)` and get the type *and* lens imported at the same time.

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Request.hs
> +        httpClient <- asks (^. #_client)
note that `view` works in a `MonadReader`, so this is also:


```suggestion
        httpClient <- view #_client
```

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Scenario.hs
> +        action runAndPersist >> return (Result "" Success)
It seems *really* wrong to me to unconditionally return `Result "" Success`. Don't we care about the result of `action`?

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            . destination (addr, 14)
Now that I know these functions are all unsafe, I have an urge to check the definition of every single one and verify that you didn't forget to set the required parameters. It would be *much* easier and simpler if this were simply:

```haskell
response <- postTransaction
    (source wallet)
    (destination (addr, 14))
```

(or whatever the right lensy thing is)

2018-12-04 17:13 UTC, parsonsmatt commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +  ) where
2 space indent

2018-12-04 17:15 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +scenario title spec = it title (successfulRequest Client.resetWalletState >> spec)
True :) and to be honest, I thought about it. Though, this is a `before` we always want and can easily forget, hence it being shoved and hidden up here :stuck_out_tongue:

2018-12-04 17:17 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    expectFieldEqual ($)
Haha, true that :+1:

2018-12-04 17:22 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +notInitialized proxy =
I am rather unsatisfied as well about this one and I knew you'd point that out :upside_down_face:  ... It's really about the end goal in the end: having the end scenario written in the most simple and readable way. Ideally, I'd like to add something at the type-level in the data-structure to mark which fields are required in such way that the whole object becomes a monoid. Fields can be either defaulted to an empty value, or we use this "Required" type-wrapper to initialize the non-defaultable fields. 

```hs
data RequestParameters = RequestParameters
    { myField :: Required String
    , otherField :: [Whatever]
    }
```

Meh, I'll try to get something better :+1:

2018-12-04 17:23 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Request.hs
> +        httpClient <- asks (^. #_client)
mind = blown.

2018-12-04 17:24 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Scenario.hs
> +        action runAndPersist >> return (Result "" Success)
Well, I caught that in the original implementation from HSpec's source code. That's how they implement the `Example (IO ())`. My two cents is that this `Result` wrapper is only used for scenario wrapping QuickCheck properties.

2018-12-04 17:27 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            . destination (addr, 14)
Well, my only regrets with the fonction vs monoid combinator approach is that, with the function, we are forced to specify every arguments and we loose some cognitive load when reading the test, trying to figure out which of those parameters are we actually acting upon. 
The monoidal combinator approach allows to only use the one that matters for the test. Doesn't buy us much and maybe it's not worth it in the end :/

2018-12-05 17:31 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Scenario.hs
> +        action runAndPersist >> return (Result "" Success)
Interesting.

Turns out `hspec` and the underlying libraries just assume an `IO` action completing at all is a success, and all test failures are done by exceptions. So if `action runAndPersist` throws, then `return` never executes!

2018-12-05 17:33 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +notInitialized proxy =
There's a concept called Monoid Actions, with a class:

```haskell
class Action m a where
  act :: m -> a -> a
```

where `m` is a Monoid or Semigroup and the laws are basically:

```
act a . act b = act (a <> b)
```

This gives a nice abstraction on "partial configurations acting on a default" where a partial configuration has an "override" `<>` operation.

However, the abstraction ends up being kind-of a lot of boilerplate for not much gain over just being specific about what you mean.

2018-12-05 18:23 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +
All those default are quite "verbose" but they make the scenarios nicer to read in the end :+1:

2018-12-05 18:24 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +
@parsonsmatt 
I'd appreciate your inputs on the ones below :upside_down_face: Some are maybe a bit ad-hoc.

2018-12-05 18:25 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Scenario.hs
> +runWithContext :: forall ctx. ctx -> SpecM ctx () -> Spec
TODO :+1:

2018-12-05 18:25 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +  ) where
TODO :+1:

2018-12-05 18:33 UTC, parsonsmatt approved these changes

2018-12-05 18:33 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +{-# INLINE[0] lens #-}
why aren't we just using `Control.Lens`? the library already depends on it iirc

2018-12-05 18:33 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    _set (s, v) = set typed (V1 $ mkCoin v) s
lgtm

2018-12-05 18:33 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/DSL.hs
> +    typed
For definitions as short as these, I'd probably condense to two lines:

```haskell
walletName :: HasType Text s => Lens' s Text
```

Note, however, that `walletName` will only work on data structures that only contain a *single* value of type `Text`, and will work on values like:

```haskell
data User = User { userName :: Text } deriving Generic
```

which is not what you want. So a `newtype WalletName = WalletName Text` might be warranted here?

2018-12-05 18:33 UTC, parsonsmatt commented on test/integration/Test/Integration/Framework/Request.hs
> +        -> m (Either ClientError (Response originalResponse))
The metadata is mostly useful for pagination

2018-12-05 18:37 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +{-# INLINE[0] lens #-}
Yeah, that was to have the definition in front of me while I was grooming haha. This is the kind of polish i told you about :upside_down_face:

2018-12-05 18:39 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    typed
Yup, thought of it and we'll probably end up doing that. I didn't want to clutter the PR with type changes in our source code but well, that's next for sure (including removing all those V1)

2018-12-06 19:22 UTC, merged