Address Pool Module tests.
input-output-hk/cardano-wallet-legacy pull request #129
Opened 2018-12-04 10:11 UTC by denisshevchenko

# Linked Issue

<Put here a reference to the issue this PR relates to and which requirements it tackles>

<p align="right">#33</p>

# Overview

<Detail in a few bullet points the work accomplished in this PR>

1. - [ ] ...

# Comments

<Additional comments or screenshots to attach if any>

¯\\\_(ツ)\_/¯

# Checklist

- [ ] I've kept this PR simple, on-the-spot, free of cosmetic changes.
- [ ] I have reviewed my commit messages and history.
- [ ] I've assigned a reviewer.
- [ ] I acknowledge my changes may require an update in the wiki.
- [ ] I have added a reference to this PR to the corresponding issue.

---

- [ ] I've checked the checklist

2018-12-04 10:45 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +      -- ** For testing purpose.
Not necessarily. Let's remove the comment :+1:

2018-12-04 10:45 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +            tooBigGap   `shouldSatisfy` isLeft
This isn't really testing 'AddressPool', is it ? Rather, this is testing `mkAddressPoolGap` constructor and our `Bounded` instance.

2018-12-04 10:45 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +            fromIntegral gap `shouldBe` validGapNum
The two tests above could actually be generated! That's the whole point of property testing after all!
For instance:

```hs
prop_generatorIsValid
    :: Int
    -> Property
prop_generatorIsValid gap =
    case mkAddressPoolGap (fromIntegral gap) of
        Left _  -> not (isWithinBound gap)
        Right _ -> isWithinBound gap
  where
    maxGap = fromIntegral (maxBound :: AddressPoolGap)
    minGap = fromIntegral (minBound :: AddressPoolGap)
    isWithinBound x = x <= maxGap && x >= minGap
```

2018-12-04 10:45 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +            addr `shouldBe` sameAddress
Here, we could use instead a small state-machine testing comparing about pool against a given model. Here, our model can just be the pool's size :stuck_out_tongue:

2018-12-04 10:45 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +    ]
Don't we have arbitrary instances for those :smile: ?

2018-12-04 11:05 UTC, denisshevchenko commented on test/unit/Test/Spec/AddressPool.hs
> +            tooBigGap   `shouldSatisfy` isLeft
Yes, this test proves that it's _impossible_ to create too small or too big gap. It's a useful test, no?

2018-12-04 11:31 UTC, denisshevchenko commented on test/unit/Test/Spec/AddressPool.hs
> +    ]
Well, no:

> No instance for (Test.QuickCheck.Arbitrary.Arbitrary Address)

2018-12-04 15:03 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +            getAddressPoolSize poolWithRandomAddresses === fromIntegral validGap
This property mixes two things:

- The validity test of `initAddressPool`
- The creation of `AddressPoolGap`

Plus.. I am not really sure what are we testing here? We can't create address pools from invalid address gap, that's a guarantee from the type system already. `initAddressPool` doesn't use a raw `Int`, it uses a `AddressPoolGap`, and since the only way to get a instance of such type is through `mkAddressPoolGap` and we already ensured that this was correct, there's no reason to test that further...

2018-12-04 15:23 UTC, denisshevchenko commented on test/unit/Test/Spec/AddressPool.hs
> +            getAddressPoolSize poolWithRandomAddresses === fromIntegral validGap
You're right, this test is unnecessary.

2018-12-05 08:22 UTC, KtorZ requested changes

2018-12-05 08:22 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +mkRandomUUID _ix = unsafePerformIO $ nextRandom
This generates *exactly one* value, once. `unsafePerformIO` is really not what you're looking for here. 
Quickcheck generates those values for you through `Arbitrary` instances ... This should be a parameter of your property, that's really what Quickcheck is for in the end....

2018-12-05 08:25 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +            monadicIO $ do
There's nothing monadic in this property to be honest .... This is all pure stuff.

2018-12-05 08:26 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +        Left _ -> property True -- Gap is invalid, just ignore it.
Then, make sure to get one as parameter instead...

```hs
prop_poolExtensionIsValid
    :: AddressPoolGap
    -> Property
prop_poolExtensionIsValid gap =
```

Again, that's the whole point of defining `Arbitrary` instances.

2018-12-05 08:26 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +                allAddresses = getAddresses pool
Nope, this we don't want to expose. `getAddresses` shouldn't exist.

2018-12-05 08:27 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +                someIndex <- run (liftIO $ randomRIO (0, length allAddresses - 1))
This should be a property parameter and not generated as part of the property.

2018-12-06 18:19 UTC, KtorZ approved these changes

2018-12-06 18:32 UTC, merged