Remove use of V1 wrapper: PassPhrase
input-output-hk/cardano-wallet-legacy pull request #135
Opened 2018-12-06 20:20 UTC by denisshevchenko

# Linked Issue

<Put here a reference to the issue this PR relates to and which requirements it tackles>

<p align="right">#</p>

# Overview

<Detail in a few bullet points the work accomplished in this PR>

1. - [ ] ...

# Comments

<Additional comments or screenshots to attach if any>

¯\\\_(ツ)\_/¯

# Checklist

- [ ] I've kept this PR simple, on-the-spot, free of cosmetic changes.
- [ ] I have reviewed my commit messages and history.
- [ ] I've assigned a reviewer.
- [ ] I acknowledge my changes may require an update in the wiki.
- [ ] I have added a reference to this PR to the corresponding issue.

---

- [ ] I've checked the checklist

2018-12-07 07:56 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +instance ToSchema Core.PassPhrase where
Here we introduce orphan instances, which we really don't want. Instead, let's come up with our own dedicated newtype: `PassPhrase` or `WalletPassPhrase`. The idea isn't to simply remove `V1` but to replace it with appropriated newtypes!

2018-12-07 15:29 UTC, akegalj approved these changes

2018-12-07 15:54 UTC, KtorZ requested changes
PR looks good, but we're missing two things:

- Golden tests
- Acid-State Migration

Ideally, we need write golden tests before making any change, such that they are written using the old code, and we control via the new code that everything is correct. 
Can you maybe issue another PR that we'll merge prior to this one, only adding at least one golden for the `ToJSON` and `FromJSON` instance, even though I am quite sure nothing got broken along the way.

But for all others, that should become the normal procedure:

1/ Golden tests
2/ Removing / Replacing V1
3/ Acid-state Migration.

2018-12-10 15:13 UTC, KtorZ commented
@denisshevchenko 

Remember to update golden tests here as a consequence of #144  :+1:

2018-12-11 08:59 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    mempty = WalletPassPhrase mempty
Let's avoid defining instances on type aliases. Could we actually remove the "SpendingPassword" alias entirely (while preserving the existing fields in various data types?)

2018-12-11 09:01 UTC, KtorZ approved these changes
LGTM :+1:

One minor gotcha that we could fix as part of another PR I believe.

2018-12-11 09:02 UTC, merged