Derive address private key from account private key
input-output-hk/cardano-wallet-legacy pull request #169
Opened 2018-12-18 20:12 UTC by akegalj

<p align="right">#41</p>

# Overview

- [ ] I have added a method to derive address private key from account private key
- [ ] I have added property tests to check the above method

# Comments

For some reason property test https://github.com/input-output-hk/cardano-wallet/compare/akegalj/41/derive-addrPrvKey-from-accPrvKey?expand=1#diff-e9a62968e1cca775db414be6d317ecadR125 fails and I have to debug where is the issue. In theory it should work

2018-12-18 20:22 UTC, akegalj commented on src/Cardano/Wallet/Kernel/Ed25519Bip44.hs
> +derivePublicKey :: EncryptedSecretKey -> PublicKey
This was just moved from the bottom of the module

2018-12-18 20:22 UTC, akegalj commented on src/Cardano/Wallet/Kernel/Ed25519Bip44.hs
> +    -- lvl5 derivation in bip44 is derivation of address chain
typo

2018-12-18 20:22 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    addrPubKey = deriveAddressPublicKey accountPublicKey change addressIx
renamed to give a bit more context to binding

2018-12-18 20:22 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isNonHardened addressIx ==> (addrPrvKey1 === addrPrvKey2)
for some reason this fails in quickcheck - should work in theory based on https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--public-child-key , so should do more debugging with it

2018-12-18 23:15 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    accEncPrvKey = mkEncSecretWithSaltUnsafe emptySalt passPhrase $ generate (BS.pack $ take 32 seed) passBytes
to address failure of this property I have tried to manually create encrypted account private key. My initial idea was that the property might be failing because generated `EncryptedSecretKey` didn't match generated `PassPhrase`, so in this version we manually create account encrypted secret key from seed and passphrase and we reuse this passphrase for child derivations.

Unfortunatelly this doesn't help and this property still fails:
```
> quickCheck $ prop_deriveAddressPublicFromAccountPrivateKey 
*** Failed! Falsifiable (after 58 tests and 46 shrinks):     
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] ++ ...
<passphrase>
ExternalChain
134217728
Just (PublicKey (XPub {xpubPublicKey = "U\t\166M\EM\175\215\161w}\237F+\174\155\161\176\v\232\202\228\SOH0[\189\151\206i\133\177\ETX\174", xpubChaincode = ChainCode "\140V\195\149\168\253\237\219/\173q\209|%\135\rJ\200H\240\208\&2\168K\165\133)<\GS\207S\188"})) /= Nothing
```
so I wonder why :| 

Any ideas?

2018-12-19 07:56 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Ed25519Bip44.hs
> +    :: ShouldCheckPassphrase    -- Weather to call @checkPassMatches@
I believe this is useless here? It was present in `deriveLvl2KeyPair` because the function was doing many things at once. Here, we do want to check the passphrase every time, don't we ?

Or at least, if needed, we'll add it later on.

2018-12-19 07:58 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- 50% slower.
Great idea :+1:

2018-12-19 08:02 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    accEncPrvKey = mkEncSecretWithSaltUnsafe emptySalt passPhrase $ generate (BS.pack $ take 32 seed) passBytes
One general remark: it's usually a good idea to narrow down the number of parameters you have and create instead, several properties. For instance, you could write this one with a fixed passphrase (or, at the very most, a Maybe with a static passphrase, or nothing), and then, another property where the key is fixed but trying out many passphrases.

2018-12-19 08:49 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    accEncPrvKey = mkEncSecretWithSaltUnsafe emptySalt passPhrase $ generate (BS.pack $ take 32 seed) passBytes
yes - that way search space will be more specialized (around those free variables)

2018-12-19 09:19 UTC, akegalj commented on src/Cardano/Wallet/Kernel/Ed25519Bip44.hs
> +    :: ShouldCheckPassphrase    -- Weather to call @checkPassMatches@
Yes - I was confused why we don't check passphrase every time. I thought its some kind of optimization. But hd wallet child key derivation doesn't happen that often (at least this is my intuition) and in most cases check is needed.

I think your suggestion is sound - lets remove it for now and we will add it later if really needed (which I doubt)

2018-12-27 08:19 UTC, KtorZ commented
@akegalj , so what's up with this one ?

2018-12-27 20:15 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isNonHardened addressIx ==> (addrPrvKey1 === addrPrvKey2)
fixed https://github.com/input-output-hk/cardano-crypto/pull/52

2018-12-27 20:15 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    accEncPrvKey = mkEncSecretWithSaltUnsafe emptySalt passPhrase $ generate (BS.pack $ take 32 seed) passBytes
fixed https://github.com/input-output-hk/cardano-crypto/pull/52

2018-12-27 20:15 UTC, akegalj commented on src/Cardano/Wallet/Kernel/Ed25519Bip44.hs
> +    :: ShouldCheckPassphrase    -- Weather to call @checkPassMatches@
Removed

2018-12-28 10:15 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- FIXME (akegalj): instead of doing this create generator for non-hardened keys.
Make sure to put those on the ticket as bullet points :+1:, otherwise, we won't likely every tackle those points...

2018-12-28 10:15 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            addressIx
I am really a big fan of this property :purple_heart:

2018-12-28 10:15 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- FIXME (akegalj): instead of doing this create generator for non-hardened keys.
Would be nice to at least make sure we aren't just comparing `Nothing` with `Nothing` at each step :man_shrugging:

2018-12-28 10:15 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +-- if account index is hardened
Comment feels wrong here :thinking: ? Shouldn't it be `address index` ?

2018-12-28 10:15 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isHardened addressIx ==> property (isJust addrPrvKey)
How come this passes :thinking: ? Shouldn't it be `property (isNothing addrPrvKey)` ?

2018-12-28 10:15 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            expectFailure prop_deriveAddressPrivateKeyHardened
Ah! `expectFailure`, I get it. This feels a bit wrong here because, we aren't expecting the property to pass even once. I find it quite confusing here and having the property being written the other way around (expecting always `Nothing` when using a hardened index) makes the intent clearer IMO. 

Don't you think?

2018-12-28 10:33 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- FIXME (akegalj): instead of doing this create generator for non-hardened keys.
> Would be nice to at least make sure we aren't just comparing Nothing with Nothing at each step

true that - will update

2018-12-28 10:35 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            addressIx
found by accident actually - but I would like to add similar property more low level, to `cardano-crypto` where it actually bellongs (its bip32 property, not bip44). 

`cardano-wallet` is checked and safe this way - but some other applications/libs which are using `cardano-crypto` might not implement this safe net - so long term it would be wise to move it to `cardano-crypto`

2018-12-28 10:42 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isHardened addressIx ==> property (isJust addrPrvKey)
fails because this property is expected to fail with `expectFailure prop_derivateAddressPrivateKeyHardened` 

Althought I am to sure is my usage of `expectFailure` correct. It seems like property succeeds if at least one failure is found (and quickcheck will stop at the first one which doesn't provide much coverage).

Alternative to `expectFailure` approach would be to cover all cases as @denisshevchenko did with https://github.com/input-output-hk/cardano-wallet/pull/169/files#diff-e9a62968e1cca775db414be6d317ecadR33 . I was not sure which one is better suited. 

https://github.com/input-output-hk/cardano-wallet/pull/169/files#diff-e9a62968e1cca775db414be6d317ecadR33 is a bit harder to read/understand in my opinion but covers both cases, where in my scenario one case is discarded by prefilter `==>`

what's your opinion on this topic?

2018-12-28 10:45 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            expectFailure prop_deriveAddressPrivateKeyHardened
would you prefer 
```haskell
isHardened addressIx ==> property (isNothing addrPrvKey)
```

or how denis covered both branches:
```haskell
     if isHardened addressIx
   	         then isNothing addrPrvKey
	         else isJust addrPrvKey
```

2018-12-28 10:55 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isHardened addressIx ==> property (isJust addrPrvKey)
Yeah, I noticed after the `expectFailure` below. The precondition arrow reads quite nicely to be honest. But I'd rather write a valid property here (so `IsNothing ...`). `expectFailure` can be use to put emphasize on things we may think of as properties but aren't in reality. Or, to cover highlight failing scenarios. 

About _precondition_ vs _if_, it'd personally favor two properties with precondition to really make the intent clear about what's being tested (also makes the failure clearer because we know exactly what part has failed). Also, if one of the cases never happens because of a poorly designed generator, then QuickCheck will give up trying to satisfy the precondition. Without instrumenting on the coverage, this will remain unnoticed in the `if .. then ... else` approach.

2018-12-28 10:56 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            expectFailure prop_deriveAddressPrivateKeyHardened
Cf comment above :)

2018-12-28 10:59 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isHardened addressIx ==> property (isJust addrPrvKey)
very good point - didn't thought about the later and quickcheck giving up

2018-12-28 11:52 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            addressIx
Added a point to #41 development plan

2018-12-28 11:58 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- FIXME (akegalj): instead of doing this create generator for non-hardened keys.
> Make sure to put those on the ticket as bullet points +1, otherwise, we won't likely every tackle those points...

added a point to #41 development plan

> Would be nice to at least make sure we aren't just comparing Nothing with Nothing at each step

pending...

2018-12-28 12:20 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- 50% slower.
added point to #41 development plan

2018-12-31 16:45 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- 50% slower.
added as a point to development plan #41

2018-12-31 16:58 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    -- FIXME (akegalj): instead of doing this create generator for non-hardened keys.
Resolved

2018-12-31 18:02 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isHardened addressIx ==> property (isJust addrPrvKey)
Implementation of this requirement requires me to implement point from #41 development plan:
> Open an issue to add arbitrary generator for hardened and non-hardened indexes and keys

as quickcheck is not able to pick big enough numbers for hardened indexes and gives up, see https://github.com/input-output-hk/cardano-wallet/pull/169/commits/96043b7e460c232c7793f76aa3ce954bda8c5344#diff-e9a62968e1cca775db414be6d317ecadR28  : 

```haskell
quickCheck $ withMaxSuccess 1000 prop_cannotDeriveAddressPublicKeyForHardenedIx 
*** Gave up! Passed only 17 tests.
```

quickcheck `verbose` modificator told me what is going on: quickcheck is picking small numbers and precondition `isHardened ix` fails most of the time. I have tried to use `Large` from quickcheck but it fails as well. So instead this refactor requires me to add two specialized generators for hardened and non hardened keys which should be fairly simple

2019-01-01 11:06 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            expectFailure prop_deriveAddressPrivateKeyHardened
Resolved with https://github.com/input-output-hk/cardano-wallet/pull/169/commits/ce4cedfe9fe0a878416dd89ea71a1f5ad25c75d9

2019-01-01 11:07 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +    isHardened addressIx ==> property (isJust addrPrvKey)
Resolved with https://github.com/input-output-hk/cardano-wallet/pull/169/commits/ce4cedfe9fe0a878416dd89ea71a1f5ad25c75d9

2019-01-01 11:07 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +-- if account index is hardened
Resolved with https://github.com/input-output-hk/cardano-wallet/pull/169/commits/ce4cedfe9fe0a878416dd89ea71a1f5ad25c75d9

2019-01-02 09:16 UTC, KtorZ commented
@akegalj This one conflicts with the previous one :no_mouth: , may you look into that please ?

2019-01-02 15:11 UTC, KtorZ requested changes

2019-01-02 15:11 UTC, KtorZ commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            addressIx
I am afraid that the two properties above aren't testing much :/ .. I was surprised at first that this particular one even pass without QuickCheck giving up (actually, the generator for `PassPhrase` isn't as broad as I thought). 

Still, the only case where the precondition may possibly (realistically) be satisfied is when the passphrase is empty. Chances to get an `EncryptedSecretKey` generated with a passphrase identical to `PassPhrase` are actually quite null here.

To get convinced, we can write:

```hs
    isJust (checkPassMatches passPhrase accEncPrvKey) ==>
         classify (passPhrase == mempty) "Empty PassPhrase" (property $ isJust addrPrvKey)
```

which yields:

```
succeeds if passwords are equal
      +++ OK, passed 100 tests (100% Empty PassPhrase).
```

2019-01-02 18:16 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            addressIx
:/ good catch!

I had a comment about that actually before last refactor and was also suspicious to see quickcheck passed the test - but was lazy to check the cause in this case :-1:  

Thanks for having a look - will add custom generator for this case.

2019-01-02 18:20 UTC, akegalj commented on test/unit/Test/Spec/Ed25519Bip44.hs
> +            addressIx
this would eventually be caught by https://github.com/input-output-hk/cardano-wallet/issues/188

2019-01-03 07:25 UTC, KtorZ approved these changes
Merging as is. We'll tackle the pending point about the test in #188

2019-01-03 07:25 UTC, merged

2019-01-03 10:15 UTC, akegalj commented
thanks - added a point to development plan of https://github.com/input-output-hk/cardano-wallet/issues/188