WIP #88 Add applying blocks via diffusion and comment out old mechanism
input-output-hk/cardano-wallet-legacy pull request #177
Opened 2018-12-21 10:34 UTC by paweljakubas

#88 

# Overview

- [x] I have added getBlocks and requestTip support in diffusion layer
- [x] The additional thread is instantiated that is responsible for downloading blocks from the node
- [x] The added mechanism is based on pull paradigm, ie., the wallet is the initiator for pulling blocks, makes sure the blocks are in line with what the node has
- [x] The same resolved blocks are created using the added mechanism as it is in case of old mechanism
- [x] apply blocks part of old mechanism is commented out  

# Comments

The thorough description of the proposed mechanism will be added very soon 
[here](https://github.com/input-output-hk/cardano-wallet/wiki/ApplyingBlocks-Rollback-After-Refactoring-Byron)

2018-12-21 11:01 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +                    return ()
Commenting out readerT mechanism

2018-12-21 11:03 UTC, paweljakubas commented on src/Cardano/Wallet/Server/Plugins.hs
> +
need this in order to use getBlocks and service MonadBlockVerify constraint

2018-12-21 11:04 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Submission/Worker.hs
> +                   -> (([HeaderHash],[HeaderHash]),Utxo)
This will probably be different types as we will switch to checkpoint based mechanism

2018-12-21 11:05 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/DB/BlockContext.hs
> +    } deriving (Eq, Show)
needed this to print resolved blocks - will clean this in the final version

2018-12-21 11:05 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/DB/Resolved.hs
> +    } deriving Show
needed this to print resolved blocks - will clean this in the final version

2018-12-21 11:07 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +        let initialUtxo = ccUtxo $ initCardanoContext genesisConfig
I have to do it in order to have initial Utxo - in the readerT mechanism it comes with Undos

2018-12-21 13:06 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
>                      mapM_ (Kernel.applyBlock w) mp
here it was the place where BListener applyBlocks was invoked

2018-12-21 13:08 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +
Instantiating dedicated diffusion ticker thread

2018-12-27 08:17 UTC, KtorZ requested changes

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +import           Pos.DB.Block
Favor explicit imports over exposing all identifiers :+1:

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +{-# OPTIONS_GHC -fno-warn-type-defaults #-}
I guess this will be removed later :upside_down_face:

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/Resolved.hs
> +    } deriving Show
Can leave it there actually. Always good to have a little debug capability.

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                                    getPrevBlock nodeId prevBlockHeader Nothing (block : blocksInThisBatch)  --
What is the flow exactly here :thinking: ? We download blocks going backward from a given a point until we reach either a certain point or, the very first block (when `toMaybe = Nothing`) ?

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                            pure $ OldestFirst blocksInThisBatch --
Is this really unexpected, or is it simply the terminal case of the recursion, once there's no more blocks to retrieve?

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                    case downloadedBlockStripped of
```hs
blocks <- getOldestFirst <$> getBlocks d nodeId from [from]
case blocks of 
```

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +            \nodeId from toNotIncluding -> do
I'd write this the other way around to make things a bit clearer:

```hs
walletGetBlocks nodeId from toNotIncluding = do
    ...
  where
    getPrevBlocks :: ...
```

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                     [lastConsumedHeader] -> do
Why is this a list if we only care about this being a singleton or.. something else? Wouldn't a `Maybe` better reflect the intent here?

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Server/Plugins.hs
> +
We will find a way around this :) ... Having it passed as an extra parameter isn't a bad choice. The reflection stuff is... not pragmatic.

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Submission/Worker.hs
> +                   => (Severity -> Text -> m ())
Please, no more variable-length indentation :(

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +    tickDiffusionFunction ((inProgressHeader, consumedHeader),utxo) = do
This sounds like something that should be in `Kernel/Diffusion` instead.

2018-12-27 08:17 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +        liftIO $ threadDelay $ 120 * oneSecond
I suggest introducing a dedicated DSL extension for this `expectNextEpochEventually` or something like this.

2018-12-27 08:17 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +                pure $ (([h1], (reverse accomodatedHeaders) ++ consumedHeader), updatedUtxo)
Wow. That's one big function which I honestly didn't try to read much :( ... Sounds like this would deserve to be clarified and decomposed a bit in smaller pieces.

2019-01-07 11:13 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +{-# OPTIONS_GHC -fno-warn-type-defaults #-}
yes, I need this for temporary logging

2019-01-07 13:23 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                                    getPrevBlock nodeId prevBlockHeader Nothing (block : blocksInThisBatch)  --
We use `getPrevBlock nodeId from toMaybe blocksInThisBatch` here. Case when `toMaybe = Nothing` is used refers to the initial situation when up till now no block was downloaded. In that case we are expected to stop when genesis block is reached. In `getPrevBlock` we download the block having `from` header and add it to blocksInThisBatch. We stop when the previous header of just downloaded block is equal to `toMaybe` (if present) or when (if `toMaybe` is absent) genesis block is found. We use for the detection of this the fact that `Block` is either `MainBlock` or `GenesisBlock`. The GenesisBlock is not included to  `blocksInThisBatch`.  In the another case we take the previous header of the just downloaded block and call `getPrevBlock` with it.

2019-01-07 13:35 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                            pure $ OldestFirst blocksInThisBatch --
As underlined above I use `getPrevBlock nodeId from toMaybe blocksInThisBatch` in a recursive fashion. Inside diffusion layer's `getBlocks` with `from` is used. This line is "insurance" that trusted node gives `[]` for the reason I cannot really anticipate here

2019-01-07 13:54 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                     [lastConsumedHeader] -> do
If servicing applying blocks only using `Maybe` would be the best. But, I would like to reuse this call in case of rollback, and in that case I will deliver here **N lastly downloaded headers*

2019-01-07 13:54 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +                    case downloadedBlockStripped of
done

2019-01-07 13:54 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Diffusion.hs
> +            \nodeId from toNotIncluding -> do
done

2019-01-07 18:23 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Submission/Worker.hs
> +                   => (Severity -> Text -> m ())
done

2019-01-07 18:23 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +    tickDiffusionFunction ((inProgressHeader, consumedHeader),utxo) = do
done

2019-01-10 15:38 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +        liftIO $ threadDelay $ 120 * oneSecond
I will do it in the separate PR

2019-01-10 15:38 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel.hs
> +                pure $ (([h1], (reverse accomodatedHeaders) ++ consumedHeader), updatedUtxo)
simplified

2019-01-11 09:38 UTC, paweljakubas commented
after successful addressing review remarks I will rebase branch against develop and squash the commits

2019-01-11 09:47 UTC, paweljakubas commented on src/Cardano/Wallet/Server/Plugins.hs
> +
I will leave it for another PR

2019-01-23 12:47 UTC, paweljakubas commented
rebased

2019-01-25 16:07 UTC, paweljakubas commented
rebased and added flag pull-mechanism to switch on this mechanism. Otherwise it readerT mechanism, push one, well tested but introducing coupling, is used

2019-01-25 16:08 UTC, paweljakubas commented
When ok, I will squash the commit

2019-02-01 13:44 UTC, KtorZ approved these changes
Merging this in a side branch for now. We still need to experiment on that and, we won't be releasing that into 1.6 anyway. Still, it doesn't make sense to keep a PR / ticket hanging for months.

2019-02-01 13:44 UTC, merged