Integration tests covering WALLETS_CREATE capability
input-output-hk/cardano-wallet-legacy pull request #178
Opened 2018-12-21 15:47 UTC by piotr-iohk

<p align="right">#</p>

# Overview

- [ ] Added integration tests covering WALLETS_CREATE capability from [Capabilities & Requirements](https://docs.google.com/spreadsheets/d/1ztF2PnnrMnkAxrhdq3LUbP1KazxcxuMrbiObTs1CuTk) document
- [ ] Failed attempt to create `expectJSONSuccess` to be used similar as as `expectJSONError`. But will go back to that later.

# Comments

2018-12-21 16:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          & assuranceLevel .~ NormalAssurance
If those aren't important for the scenario (since the wallet is deleted right after), I'd recommend to simply go with:

```hs
     fixture <- setup $ defaultSetup
           & initialCoins .~ [1000111]
```

This `initialCoins` makes sense here in order to have had some activity on the wallet before trying to restore it.

2018-12-21 16:39 UTC, KtorZ requested changes
Great stuff in there @piotr-iohk ! Impressive :stuck_out_tongue: 

There's room for more separation between scenarios however, and some simplification to keep the code tidy.

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
if the goal is just to make a successful request, then, you can just go with 

```hs
       deletion <- successfulRequest $ Client.deleteWallet
           $- (fixture ^. wallet . walletId)
```

:+1:

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
Minor things, but comma should be aligned with the brackets here :)

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
So this is a nice case for a new "expectation" that could just be plugged in with the others above

```hs
    verify restoration
        [ ...
        , expectBalanceEqual 1000111
        ]
```

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
Same as above :+1:

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          & assuranceLevel .~ NormalAssurance
Same as above :+1:

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
So, if you intend to make some assertions on a request, use `request` instead of `successfulRequest`. The later is really for request you want to fire without caring much about the result, but still making sure they succeeded.

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
5 & 6 sounds like a separate scenario to me, different from what's tested in 1,2,3 & 4?

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +      }|]
There's no need for an unsafe request here, we gotta define a proper setter for the spending password instead :smile:

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c6"
This doesn't quite match the title :p Password is an hex string, the length is incorrect thought. I'd go for two separate scenarios here as well.

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +      response <- unsafeRequest ("POST", endpoint) $ Just $ [json|{
I'd recommend to just write

```hs
unsafeRequest("POST", "api/v1/wallets") $ Just $ [json|{ ...
```

The combinator `(</>)` helps to combine `Text` with non-text types you may get from a previous response like a `WalletId` or `AccountIndex`. But as long as you just have plain text, no need for this :)

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
So, well, actually three separate scenario then ^^. The idea is to really keep scenario about testing one and one thing. This way, when one of them fails, we can quickly identify the reason why it's failing. Otherwise, it's not necessarily obvious to know where in a scenario things have failed.

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            & mnemonicWords .~ testBackupPhrase
Note that there's no need to have a custom backupPhrase here, we could just leave this as `setup defaultSetup` and use the one from the fixture anyway.

2018-12-21 16:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +      }|]
again, these should be two separate scenarios.

2018-12-21 17:27 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          & assuranceLevel .~ NormalAssurance
ok.

2018-12-21 17:27 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
ok.

2018-12-21 17:27 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
ok.

2018-12-21 17:27 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
ok.

2018-12-21 17:27 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          & assuranceLevel .~ NormalAssurance
ok.

2018-12-21 17:36 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
This was actually a workaround proposed by you. :) I wanted to use `walletId` returned by this response in the next response, like:

```      
      getAgainResp <- request $ Client.getWallet
                      $- (createResp ^. walletId)
```
and since the result of `successfulRequest` is `response` then it was easier, I guess, than with the `request` which returns `Either...`

2018-12-21 17:47 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
ok

2018-12-21 17:50 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c6"
ok

2018-12-21 17:56 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +      response <- unsafeRequest ("POST", endpoint) $ Just $ [json|{
oh, thanks :)

2018-12-21 17:57 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
sure, separated.

2018-12-21 17:58 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            & mnemonicWords .~ testBackupPhrase
ok

2018-12-21 18:30 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Request.hs
> +        -- replace `x` with `traceShow x x` for having Json responses in the test log
We'll have to remove this :) ... Let's not commit commented out code, and debug artifacts. By the by, I just realized you could have go with `print` in the scenarios if you just needed to debug a particular response... 

```hs
do
    response <- request $ .... 
    print response
    ....
```

2018-12-21 18:33 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
Hehe, got you, was lacking a bit of context here maybe :upside_down_face: 
So, my suggestion: if what you need is the wallet id, it's already in the fixture :sweat_smile:  ... So you don't need the one from the previous request, the ID is unique per wallet and strictly determined by the mnemonic. If you use a same mnemonic, you get the same id (hey look, an internal requirement / capability here :D)

2018-12-21 18:36 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +    scenario "WALLETS_UPDATE_01 - updating a wallet persists the update" $ do
Let's separate PRs here and have UPDATE_xx as part of another one :+1:

2018-12-21 21:57 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +      }|]
ok

2018-12-21 21:59 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +    scenario "WALLETS_UPDATE_01 - updating a wallet persists the update" $ do
this one was already there. Just added the WALLETS_UPDATE_01 and some additional requests, which I now see are unnecessary, so removing them.

2018-12-21 22:01 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +      }|]
so once we have it we can update the test? :)

2018-12-21 22:04 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
Well, trying to add it, but failing...
```

expectBalanceEqual
    :: (MonadIO m, MonadFail m, Show a, Eq a)
    => a
    -> Either ClientError a
    -> m ()
expectBalanceEqual = expectFieldEqual amount
```

2018-12-21 22:04 UTC, piotr-iohk commented on test/integration/Test/Integration/Framework/Request.hs
> +        -- replace `x` with `traceShow x x` for having Json responses in the test log
ok

2019-01-02 15:14 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +--     Right a -> T.unpack a `shouldContain` excerpt
This should better be in a ticket than as commented-out code :+1:

Comments should be reserved for precisions and explaining _why_; we do not want commented-out code, unless if used to illustrate usage of a function in a documentation header.

2019-01-02 15:15 UTC, KtorZ commented on test/integration/Test/Integration/Framework/Request.hs
> +
To be removed :smile:  
I think this was added to make the code compile with the `debug` helper. Not needed anymore.

2019-01-02 15:43 UTC, KtorZ requested changes

2019-01-02 15:43 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        "spendingPassword": "541"
`"541"` is actually a valid base16 string :upside_down_face:  
Perhaps `[]`, `541`, `null` or `"patate"` are better candidates here :+1:

2019-01-02 15:43 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        [ expectJSONError "Error in $.spendingPassword: suffix is not in base-16 format"
If this passes, then the error message is slightly wrong.

2019-01-02 15:43 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        ]
I am starting to think that we could make use of a combinator that would run a scenario with both "restore" and "create" operation. What do you think? We have quite many cases that are kinda duplicated because of this. Would be nice to only write things once, but get both tested seamlessly.

2019-01-02 15:43 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        ]
This could just be `successfulRequest_ $ ...` , if the only thing expected is a success, then, there's no need for a verify clause :+1:

2019-01-02 15:43 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        & assuranceLevel .~ StrictAssurance
Note: you don't need to provide backup phrases here. They'll just be generated arbitrarily for each wallet.

2019-01-02 15:43 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        [
Yeah, I was using this pattern as a way to show that assertions are somewhat isolated and don't interfere with each other.. I guess it's more confusing than anything else. Especially with a 4th case `getWalletResp <- ...` after :disappointed:

2019-01-03 11:37 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        [ expectJSONError "Error in $.spendingPassword: suffix is not in base-16 format"
yes, indeed. It passes.

2019-01-03 11:38 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        "spendingPassword": "541"
Ah, ok. I'll add tests with those values too.

2019-01-03 11:39 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        ]
Yes, that would be thing to have.

2019-01-03 11:42 UTC, piotr-iohk commented on test/integration/Test/Integration/Framework/DSL.hs
> +--     Right a -> T.unpack a `shouldContain` excerpt
ok

2019-01-03 11:43 UTC, piotr-iohk commented on test/integration/Test/Integration/Framework/Request.hs
> +
ok

2019-01-03 11:57 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        [
My motivation for using that sequence here was that... it didn't work for some reason otherwise (i.e. without having all those 3 requests in the sequence). I suppose that the reason was simply faulty indentation I had before. Removing it now.

2019-01-03 12:00 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        & assuranceLevel .~ StrictAssurance
ok. From my perspective sometimes it's more explicit and readable for the test to have it. But perhaps no in this particular case.

2019-01-03 12:05 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        ]
ok

2019-01-03 13:04 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +          ]
ok

2019-01-03 13:06 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        "spendingPassword": "541"
Actually for `"spendingPassword": null` the wallet is created successfully, but I guess that it is expected?

2019-01-03 13:26 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        [ expectJSONError "Error in $.spendingPassword: suffix is not in base-16 format"
Raised bug https://github.com/input-output-hk/cardano-wallet/issues/193

2019-01-04 08:22 UTC, KtorZ approved these changes
:tada:

2019-01-04 13:27 UTC, merged