API Endpoint for Addresses a la BIP-44: API endpoint, first version.
input-output-hk/cardano-wallet-legacy pull request #182
Opened 2018-12-27 09:52 UTC by denisshevchenko

<p align="right">#32</p>

# Overview

- [ ] I have ...

# Comments

2018-12-27 10:56 UTC, KtorZ requested changes

2018-12-27 10:56 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +      -- public key.
Sounds like we would need a new type instead of extending this one. The `createEosAddress` ain't going to return `CreateAddressKeystoreNotFound` or `CreateAddressHdRndAddressSpaceSaturated`.

2018-12-27 10:56 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +    let accountAddresses = IxSet.toList $ addressesByAccountId snapshot accId
This looks up in `_hdWalletAddresses` from the `HdWallets` in the snapshot. We haven't unified `HdWallets` and `EosHdWallets` yet so this won't work for now, but should work in the future.
Beside, lines 205 to 220 could be replaced with: 

```hs
let newAddressIx = size (snapshot ^. hdWalletsAddresses)
```

2018-12-27 10:56 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +            return $ Left CreateAddressUnableToDeriveEosAddressPublicKey
What about `CreateAddressHdSeqGenerationFailed` to make this a bit more aligned with rnd errors.

2018-12-27 15:21 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +    let accountAddresses = IxSet.toList $ addressesByAccountId snapshot accId
> This looks up in _hdWalletAddresses from the HdWallets in the snapshot.

Of course! Since we already have `_hdWalletsAddresses` (and addresses for EOS-wallets are the same `Core.Address` as for FOS-wallets) - I thought that we have to use this `(IxSet (Indexed HdAddress))` (and all existing functions/lenses) for working with EOS-wallet's addresses.

2019-01-04 08:52 UTC, KtorZ requested changes
This PR has to be separated in smaller chunks. One candidate for a first PR would be the unification between `EosHd` types and `Hd` types; this is required before we introduce a way for creating new HD addresses. 

Try to keep PR concise and on-the-spot (i.e. about one thing). If several classes of changes have to be introduced to tackle a particular task, make sure to split them across several PRs :+1:

2019-01-04 08:52 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    , neweosaddrEosWalletId  :: !EosWalletId
No need for a newtype here for `EosWalletId`. We can re-use `WalletId` :+1:

2019-01-04 08:52 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +                        eosHdAddress = EosHdAddress eosHdAddressId (InDb newAddress)
I saw nowhere in your development plan something about re-using our existing hierarchy of HD types (`HdRootId`, `HdAccountId` and `HdAddressId`. 
In the long run, we do want that instead of carrying around new `EosHd` types. Not only have they the same representation, but they also have the same semantic. In the end, they're the same type :+1:

We could move on with this PR, and make another round of cleanup after that to replace all the `EosHd***` types with their `Hd` equivalent but that sounds like a lot of code introduced in this PR that we'll have to remove afterwards.

2019-01-04 08:52 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +            case deriveAddressPublicKey accPublicKey ExternalChain newAddrIx of
Not sure we will only derive addresses on the external chain. We don't really make the difference for F.O.S addresses but it will matter here. I'd suggest to move the ChainCode to the function parameters and let the caller decides :+1:

2019-01-04 08:52 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +                Nothing -> return $ Left $ CreateEosAddressHdSeqGenerationFailed eosAccId
Now that I look at it, I think we could be more specific here. The only way we reach this `Nothing` branch would be because the `newAddrIx` is out of the non-hardened bound. Meaning that, we're running out of addresses. 
That's quite unlikely, but it would be great if the error could tell us about it:

`CreateEosAddressNoMoreAddresses` or something like this :+1:

2019-01-08 06:55 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +    , neweosaddrEosWalletId  :: !EosWalletId
You're right, it's just a wrapper around `Text`, as well as `WalletId`.

2019-01-10 12:26 UTC, denisshevchenko commented
Closed, because of bunch of smaller PRs with corresponding changes.

2019-01-10 12:26 UTC, closed without merging