[DEVOPS-1199] Add cardano-wallet-tool CLI and easy API
input-output-hk/cardano-wallet-legacy pull request #197
Opened 2019-01-04 06:03 UTC by rvl

# Overview

Part of https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1199

- Add `cardano-wallet-tool` CLI for using and testing the wallet backend.
- Add a glue API which makes it easy to set up a wallet client in `ghci`.
- Set up stack/nix integration

# Comments

```
Usage: cardano-wallet-tool ([--state-dir DIRECTORY] | ([--cert FILENAME]
                           [--key FILENAME] | [--pem FILENAME])
                           [--cacert FILENAME]) [-k|--insecure] [HOST:PORT]
                           [-p|--path PATH] COMMAND
  Connect to the API of a running Cardano Wallet backend.

Available options:
  --state-dir DIRECTORY    Wallet state directory containing "tls" subdirectory
                           with certificates
  --cert FILENAME          X509 certificate file
  --key FILENAME           Certificate key file
  --pem FILENAME           Combined X509 certificate and key file
  --cacert FILENAME        CA certificate chain for authenticating the server
  -k,--insecure            Skip server certificate authentication
  HOST:PORT                Wallet API host and port to connect to
  -p,--path PATH           Base URL path
  -h,--help                Show this help text

High-level commands
  wait-for-sync            Poll wallet until it has fully synced its chain
  wait-for-restore         Poll wallet until the restore operation is complete

Basic API calls
  node-info                Query node info
  create-wallet            Create a new wallet from mnemonic
  restore-wallet           Restore a wallet from mnemonic
  delete-wallet            Delete a wallet
  list-accounts            Retrieve full list of accounts in wallet
  delete-account           Delete account
  list-addresses           List addresses
  list-wallets             List wallets
  send-transaction         Send transaction to one or multiple target addresses
  estimate-fees            Estimate fees for a transaction
  list-transactions        Get transaction history
  get-utxo-statistics      Get UTxO distribution of wallet
```

2019-01-04 08:58 UTC, KtorZ commented
Sweet stuff in there :) 
Haven't yet review any of this but will come to that eventually. 

Just some side cosmetic notes: 

-I had plans to group a bit all executables we have spread across folders into an `app` folder (as the default/standard stack approach) in a similar fashion to what was done in [cardano-sl/cluster](https://github.com/input-output-hk/cardano-sl/tree/develop/cluster)
That'd be the same for this one. Seemingly, let's go for `cardano-wallet-client` rather than tool which is a bit too generic in my opinion.

I like the idea. Will give a more useful feedback ASAP.

2019-01-07 11:19 UTC, rvl commented
Cool, thanks. The CLI is clearly an initial version and not complete, but we can decide what needs to be done in this first PR vs what can be done in subsequent PRs.

I have changed the name, good idea.

I have also moved the code into the main `cardano-wallet.cabal` package. However I think it might be better as a separate package. This is because it adds code and dependency bloat to the cardano-wallet library, and also because multi-package projects are well-supported by `stack` and `cabal new-build`.

2019-01-08 12:24 UTC, KtorZ requested changes
A first pass on review. There's quite a lot so I mostly skimmed through it for now. I'll try to play with the content and give more useful feedback a bit later.

2019-01-08 12:24 UTC, KtorZ commented on app/sync-plot/Main.hs
> +import           Graphics.Rendering.Chart.Backend.Cairo
Let's use explicit imports for `Options.Applicative` & `Graphis.Rendering.Chart.Backend.Cairo` :+1:

2019-01-08 12:24 UTC, KtorZ commented on app/sync-plot/Main.hs
> +{-# LANGUAGE RecordWildCards   #-}
We don't much like this one anymore I've heard :smile:

2019-01-08 12:24 UTC, KtorZ commented on app/sync-plot/Main.hs
> +      else fail "Incorrect record array length"
Can't we rely on generics for this? Is the `DataFile` format constraints or is a something we define?

2019-01-08 12:24 UTC, KtorZ commented on app/sync-plot/Main.hs
> +    handle (Left err) = die err >> pure (DataFile [] "")
Doesn't `die` terminates the program? What's the need for `>> pure ...` ?

2019-01-08 12:24 UTC, KtorZ commented on app/sync-plot/Main.hs
> +  toFile (def & fo_format .~ formatFromFileName outfile) outfile $ do
Minor thing but this function could be pure and would benefits from a separation between the plot construction and the writing to file. Having run more like:

```hs
run PlotOptions{..} = do
  df <- loadRecords poInputFile
  let plot =  plotRecords poPlot poExtraTitle poPlotLeft poPlotRight df
  toFile (def & fo_format .~ formatFromFileName outfile)
```

2019-01-08 12:24 UTC, KtorZ commented on app/wallet-client/Main.hs
> +import           Cardano.Wallet.Client.Easy
Same as above, please, favor explicit imports.

2019-01-08 12:24 UTC, KtorZ commented on app/wallet-client/Main.hs
> +main = exitWith =<< uncurry run =<< execParser opts
You don't like `do` notation, do you :trollface: ?

2019-01-08 12:24 UTC, KtorZ commented on app/wallet-client/README.md
> +Start a wallet using `stack exec cardano-node -- ....`
Hopla, this is now `cardano-wallet-server`

2019-01-08 12:24 UTC, KtorZ commented on app/wallet-client/README.md
> +   equivalent `curl` command-line.
I like the idea :o

2019-01-08 12:24 UTC, KtorZ commented on cardano-wallet.cabal
> +
Can't these additions be made to the `wallet-client` executable instead :thinking:  ?

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +  , SyncThroughput(..)
I think the type was opaque for a reason :sweat_smile:

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +module Cardano.Wallet.Client.CLI.Options where
What about having this as a `other-module` of the cardano-wallet-client ?

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +data Action m = WaitForSync (Maybe ProcessID) (Maybe FilePath)
Minor style recommendation: no more variable-length vertical indent please :pray: Going to the line with a fixed-length vertical alignment plays better with git in the long run.

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/CLI/ProcessUtil.hs
> +#endif
So this won't be working at all for windows? Should we even build the CLI on windows?

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/HttpsSettings.hs
> +        }
Looks heavily inspired from: https://github.com/input-output-hk/cardano-sl/blob/develop/node/src/Cardano/Node/Manager.hs

Any reason why not to use it? (The only _true_ difference I could spot was the `AuthenticateServer` addition.

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/Easy.hs
> +               , unBlockchainHeight <$> nfoBlockchainHeight resp )
Sounds a lot like: https://github.com/input-output-hk/cardano-sl/blob/develop/cluster/src/Cardano/Cluster.hs#L131

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +  where pemConfig pem = ClientAuthConfig pem pem
why bother with the `pem` here :thinking: ? This is merely useful when using with `cURL` but I am not sure it buys us anything here.

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +    path = strOption (long "path" <> short 'p' <> value "" <> metavar "PATH" <> help "Base URL path")
Note, we already have parsers for `NetworkAddress`. I'd advise to piggy-back on them and then, translate `NetworkAddress` to `BaseUrl` whenever needed (as in:)

https://github.com/input-output-hk/cardano-sl/blob/develop/cluster/src/Cardano/Cluster/Util.hs#L379-L381

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/Wait.hs
> +  _ == _ = False
Indentation is 2-space all over this file. That is weird. Is your editor picking up the `.editorconfig` at the root of the repository?

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/Wait.hs
> +  toJSON e = String (show e)
What about using `Generics` here too :) ?

2019-01-08 12:24 UTC, KtorZ commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +-- Little option parsers
We're on the verge of reviewing our node's CLI parsers and structure. It might make sense to include all those in the list to have them centralized.

2019-01-08 19:02 UTC, parsonsmatt requested changes
The PR overall looks good, but the style is very different from existing code on this repo. Please enable `editorconfig` for your editor, and it will pick up the indentation and line-length settings for the repo.

Additionally, please favor indentation and alignment that is consistent in the face of edits and renaming. This usually means that things that are to be vertically aligned should be aligned by a newline and the appropriate indentation level for that bit. Eg:

```haskell
data Foo = Foo 
         | Bar
```

If I add a type to `Foo` or change the name, then I must also realign the constructors. However,

```haskell
data Foo
    = Foo
    | Bar
```

This layout is more resilient to edits, allowing a diff to be cleaner and easier to read.

2019-01-08 19:02 UTC, parsonsmatt commented on app/sync-plot/Main.hs
> +  plotRecords poPlot poExtraTitle poPlotLeft poPlotRight poOutputFile df
This repo uses 4 space indent. Please enable `editorconfig` for your editor so that it will automatically pick up these things.

2019-01-08 19:02 UTC, parsonsmatt commented on app/sync-plot/Main.hs
> +data Record = Record Double [Double] deriving (Show)
Please include a newline indent between datatypes.

I'd like to see a bang pattern on the `Double` field, or `StrictData` enabled for the module.

I'd prefer to see a record field for these entries to more clearly indicate what they are.

2019-01-08 19:02 UTC, parsonsmatt commented on app/sync-plot/Main.hs
> +  , dfStartTime :: Text
A start time should not be a `Text` value -- `UTCTime` is more appropriate. Given that the parser below defaults to empty string, `Maybe UTCTime` is likely the right choice.

2019-01-08 19:02 UTC, parsonsmatt commented on app/sync-plot/Main.hs
> +      else fail "Incorrect record array length"
We could actually use `DerivingVia` for this one, but we're not on 8.6 yet.

2019-01-08 19:02 UTC, parsonsmatt commented on app/sync-plot/Main.hs
> +      else fail "Incorrect record array length"
Please include diagnostics to make debugging this easier, like:

```suggestion
      else fail 
          $ "Incorrect record array length for Record, expected 2 entries but got: " 
          ++ show v
```

2019-01-08 19:02 UTC, parsonsmatt commented on app/wallet-client/README.md
> +## Easy client functions and CLI for Cardano Wallet API
Fantastic documentation, thanks! :smile:

2019-01-08 19:02 UTC, parsonsmatt commented on cardano-wallet.cabal
> +
I am personally in favor of tiny executables and big libraries, makes it a lot easier to factor stuff out and write tests later.

2019-01-08 19:02 UTC, parsonsmatt commented on src/Cardano/Wallet/API/V1/Types.hs
> +  , SyncThroughput(..)
Yeah, we should either expose an accessor or the relevant client should use `mkSyncThroughput`.

2019-01-08 19:02 UTC, parsonsmatt commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +data Action m = WaitForSync (Maybe ProcessID) (Maybe FilePath)
Agree, please newline at the `=` so everything has a constant 4 space indent :smile: 

```haskell
data Action m
    = WaitForSync ...
    | WaitForRestore ....
    | forall a. ....
```

2019-01-08 19:02 UTC, parsonsmatt commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +              | WalletEndpointVoid (WalletCallVoid m) -- ^ Wallet API call with empty response
However, since you're using an existential, I'd rather see the `GADTs` syntax used here.

2019-01-08 19:02 UTC, parsonsmatt commented on src/Cardano/Wallet/Client/Easy.hs
> +                 deriving (Show, Typeable)
Variable length alignment, please newline before the `=` and align on the 4 space boundary.

2019-01-08 19:02 UTC, parsonsmatt commented on test/unit/Test/Spec/Client/Wait.hs
> +module Test.Spec.Client.Wait (spec) where
Great tests :smile:

2019-01-08 19:02 UTC, parsonsmatt commented on test/unit/Test/Spec/Client/Wait.hs
> +spec = before mkTestWalletClient $ do
`beforeAll` is probably more appropriate; this will create a new wallet client before each spec. `beforeAll` will share the created wallet client among all specs.

2019-01-09 07:30 UTC, rvl commented
@KtorZ @parsonsmatt Thanks very much for the review comments. I have addressed most of them but am not finished yet.

2019-01-09 07:33 UTC, rvl commented on app/sync-plot/Main.hs
> +import           Graphics.Rendering.Chart.Backend.Cairo
Done.

2019-01-09 07:36 UTC, rvl commented on app/sync-plot/Main.hs
> +    handle (Left err) = die err >> pure (DataFile [] "")
Universum has `die :: String -> IO ()`, so I changed it to be the one from `System.Exit`.

2019-01-09 07:36 UTC, rvl commented on app/sync-plot/Main.hs
> +  toFile (def & fo_format .~ formatFromFileName outfile) outfile $ do
Yes, that is much better, done.

2019-01-09 07:37 UTC, rvl commented on app/wallet-client/README.md
> +Start a wallet using `stack exec cardano-node -- ....`
Updated

2019-01-09 07:44 UTC, rvl commented on src/Cardano/Wallet/Client/CLI/ProcessUtil.hs
> +#endif
Running the CLI on Windows (as part of tests) is actually one of the reasons I wrote this code. The `wait-for-sync --pid` option won't work yet on Windows so I have marked it as TODO.

2019-01-09 07:47 UTC, rvl commented on src/Cardano/Wallet/Client/HttpsSettings.hs
> +        }
Yes, it's the `AuthenticateServer` option. They should be de-duplicated. Will the `mkHttpsManagerSettings` function stay in `cardano-sl` or move elsewhere?

2019-01-09 07:55 UTC, rvl commented on src/Cardano/Wallet/Client/Easy.hs
> +               , unBlockchainHeight <$> nfoBlockchainHeight resp )
Yes it does the same thing, plus logging the timing information, handling Ctrl-C, and giving up if a PID has gone. The wait function uses `Control.Retry`, but I'm not sure if that helped.

2019-01-09 07:59 UTC, rvl commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +  where pemConfig pem = ClientAuthConfig pem pem
I want this program to inter-operate well with users' configurations. If they have generated certificates themselves then this option will help. In any case, it's easier to supply just `--pem` instead of both `--cert` and `--key`.

2019-01-09 08:04 UTC, rvl commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +    path = strOption (long "path" <> short 'p' <> value "" <> metavar "PATH" <> help "Base URL path")
I have changed it to use `Pos.Util.OptParse.fromParsec Pos.Core.NetworkAddress.addrParserNoWildcard`. The `BaseUrl` should stay here because then the user can provide an API base URL. This is for interoperability with the interesting/weird setups that users are likely to try -- for example, running the wallet behind a reverse proxy.

2019-01-09 08:06 UTC, rvl commented on src/Cardano/Wallet/Client/Wait.hs
> +  _ == _ = False
I have now enabled EditorConfig in Emacs.

2019-01-09 08:06 UTC, rvl commented on app/sync-plot/Main.hs
> +  plotRecords poPlot poExtraTitle poPlotLeft poPlotRight poOutputFile df
Done.

2019-01-09 08:10 UTC, rvl commented on app/sync-plot/Main.hs
> +  , dfStartTime :: Text
Done.

2019-01-09 08:10 UTC, rvl commented on app/sync-plot/Main.hs
> +      else fail "Incorrect record array length"
Good idea, done.

2019-01-09 08:12 UTC, rvl commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +              | WalletEndpointVoid (WalletCallVoid m) -- ^ Wallet API call with empty response
Done.

2019-01-09 08:12 UTC, rvl commented on test/unit/Test/Spec/Client/Wait.hs
> +spec = before mkTestWalletClient $ do
Done

2019-01-09 08:14 UTC, rvl commented on src/Cardano/Wallet/API/V1/Types.hs
> +  , SyncThroughput(..)
What would be the best way to log the throughput value as a number that can be stored in a JSON file and then later plotted?

2019-01-09 08:18 UTC, rvl commented on src/Cardano/Wallet/Client/Wait.hs
> +  toJSON e = String (show e)
I don't think it's possible because there is no `Generic` instance of `SomeException`.

2019-01-24 02:00 UTC, rvl commented on src/Cardano/Wallet/Client/CLI/Options.hs
> +module Cardano.Wallet.Client.CLI.Options where
It could, but I have a unit test for a function in this module.

Cabal new-build internal libraries might provide a way of keeping non-core wallet code out of the main library.

2019-01-24 02:01 UTC, rvl commented on app/sync-plot/Main.hs
> +{-# LANGUAGE RecordWildCards   #-}
:smile: Is `RecordWildcards` a problem in this file of this repo? The data type and usage are in the same file, and the record fields have prefixes.

2019-01-24 02:02 UTC, rvl commented on app/sync-plot/Main.hs
> +      else fail "Incorrect record array length"
I intentionally wrote instances for this because they are short and the JSON format should look like a normal JSON data file, not something weird and haskelly. Is it OK? (the alternative is to define `genericParseJSON customOptions`)

2019-01-24 02:03 UTC, rvl commented on app/sync-plot/Main.hs
> +data Record = Record Double [Double] deriving (Show)
Done.

2019-01-24 02:13 UTC, rvl commented on src/Cardano/Wallet/Client/Easy.hs
> +                 deriving (Show, Typeable)
Fixed.

2019-01-24 02:14 UTC, rvl commented
@ktorz @parsonsmatt Thanks for the reviews, I apologise for the delay (leave, other things, etc). I have rebased on develop and addressed/responded to your comments so far.

I also implemented a few more CLI commands for API endpoints (although the entire API is not covered yet).

About code formatting (everyone's favourite topic I know). I have fixed it, but are half-indented `where`s acceptable? That means the actual bindings are indented 4 spaces instead of 8.

What else should be done for this PR?

2019-01-24 13:30 UTC, KtorZ commented
@rvl Apologize for the time it takes but priority has been quite elsewhere at the moment for us. And this is extra code to maintain and test (even though, mind you, it is much appreciated). 
Since it's also a bit out-of-the-loop for us, we haven't really included this in our QA pipeline which should be done at some point. 

Might I can put that on @piotr-iohk radar. Would be a nice idea to play with it and see if things are working smoothly. This is of course of a lower priority vs anything about decoupling or BIP-44 :+1:

2019-01-25 09:22 UTC, rvl commented
OK I'll follow up with QA and see how I can assist them.
This tool is something that I need for devops work, because there is currently no easy way to use the wallet API.
Additionally, I have built the Windows chain sync acceptance tests on top of this program. We really need automated sync tests running on Windows.
What's the best way to get this merged? We don't want to have a long-running feature branch.

2019-01-25 10:16 UTC, KtorZ commented
I understand and I do agree with you that the situation is not practical here. What I am truly afraid of here is that, as soon as this lands on this repository, it becomes (eventually) the wallet's team responsibility. And that is something that comes a bit "out of nowhere" for us because it wasn't planned nor discussed with any of us :disappointed: 
We can't just afford this extra work at the moment. My recommendation here would be to have that maybe as _another repository_, maintained and managed by devops or, maybe a dedicated team later once we've agreed on spending time and resources on building and improving such tool.

2019-01-28 13:59 UTC, KtorZ commented
Closing as per last comment + private conversation.

2019-01-28 13:59 UTC, closed without merging