Integration tests for WALLETS_LIST_02
input-output-hk/cardano-wallet-legacy pull request #217
Opened 2019-01-09 15:40 UTC by piotr-iohk

<p align="right">#</p>

# Overview

- [ ] I have added tests for WALLETS_LIST_02

# Comments
This can be addressed in subsequent PR or in this one, but:
 
- I'm missing method like `expectClientHttpError` method for asserting the `ClientHttpError` message
e.g.
```
expectClientHttpError
    :: (MonadIO m, MonadFail m, Show a)
    => String
    -> Either ClientError a
    -> m ()
expectClientHttpError excerpt = \case
    Right a -> wantedErrorButSuccess a
    Left (ClientHttpError (ServantError (DecodeFailure t r))) ->
        -- here I would like to get r.responseBody and make sure it contains excerpt
    Left e ->
        fail $ "expectClientHttpError: got something else than a ClientHttpError (ServantError (DecodeFailure t r)) failure: " <> show e
```

- also to move forward I need to get some examples on how to use `Sort` and `Filter` in the safe/typed Client

2019-01-09 15:42 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            in case (title == "1 wallet; page=9223372036854775807 & per_page=50 => 0 wallets returned") of
This test fails due to BUG https://github.com/input-output-hk/cardano-wallet/issues/213, hence made this scenario as pending...

2019-01-09 15:45 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +
This particular test scenario fails due to BUG https://github.com/input-output-hk/cardano-wallet/issues/213, hence made it pending...

2019-01-09 15:46 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +
For now I made this one pending because setting up 3 wallets here was causing:
```
uncaught exception: IOException of type UserError
       user error (expectTxStatusEventually: waited too long for statuses.)
```

2019-01-09 19:40 UTC, parsonsmatt submitted a review, later dismissed

2019-01-09 19:40 UTC, parsonsmatt commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        forM_ matrix $ \(title, wallets_number, page, per_page, expectations) ->
```suggestion
        forM_ matrix $ \(title, walletsNumber, page, perPage, expectations) ->
```

Haskell variables should be camel cased.

2019-01-09 19:40 UTC, parsonsmatt commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +
You can mark a scenario pending with `pendingWith`. It may be necessary to write a lifted version of that function. But it should be:

```haskell
scenario title $ do
  pendingWith "This test fails due to bug #213"
  test
```

That way we get a note in the code that it is pending.

2019-01-09 19:40 UTC, parsonsmatt commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            in case (title == "1 wallet; page=9223372036854775807 & per_page=50 => 0 wallets returned") of
To remove ambiguity, this string should be factored out to a common value and reused rather than copy-pasted.

2019-01-09 19:40 UTC, parsonsmatt commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +
Rather than `xscenario`, use `scenario`, and `pendingWith` with a note that says *why* it is failing.

2019-01-11 10:48 UTC, KtorZ requested changes

2019-01-11 10:48 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +pendingWith = liftIO . H.pendingWith
:+1:

2019-01-11 10:48 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    Right s -> length s `shouldBe` l
I'd recommend making this one slightly more generic such that it works with both `List` and `NonEmpty.List`. 
```suggestion
import qualified Data.Foldable as F

expectListSizeEqual
    :: (MonadIO m, MonadFail m, Foldable xs)
    => Int
    -> Either ClientError (xs a)
    -> m ()
expectListSizeEqual l = \case
    Left e   -> wantedSuccessButError e
    Right xs -> length (F.toList xs) `shouldBe` l
```

2019-01-11 10:48 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    Right s -> (view getter $ s!!(i - 1)) `shouldBe` a
Sweet :smile: !
Yet, this will blow up if the list is too small and also, elements are 0-indexed, it will be better to preserve that in the function arguments to not make it counter-intuitive.

Also, I'd make more re-use of the existing code and not re-write the getter machinery.

```suggestion
expectListItemFieldEqual 
    :: (MonadIO m, MonadFail m, Show a, Eq a)
    => Int
    -> Lens' s a
    -> a
    -> Either ClientError [s]
    -> m ()
expectListItemFieldEqual i getter a = \case
    Left _ -> expectFieldEqual getter a
    Right s 
      | length s > i -> expectFieldEqual getter a (Just (s !! i))
      | otherwise    -> fail $
        "expectListItemFieldEqual: trying to access the #" <> show i <> 
        " element from a list but there's none! Here's the list: " <> 
        show s
```

2019-01-11 10:48 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                    False -> scenario title $ test
`pendingWith` actually "interrupts" the test scenario. So you could just avoid the `let ... in` binding an go with:

```
do
    forM_ ([1..walletsNumber]) $ \name -> do
        when (title == failingScenario) $
            pendingWith ...

        -- rest of the rest
```

2019-01-15 11:56 UTC, piotr-iohk commented
I have implemented requested changes and added new tests for WALLETS_LIST_03 and 04(Part of the tests is made pending due to #220), rebased. . Please review @KtorZ and/or @parsonsmatt. Thanks!

2019-01-17 11:09 UTC, KtorZ requested changes

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        let endpoint = "api/v1/wallets?id=" <+> ( fromWalletId $ walletIds !! 0 )
I believe you don't need this custom `<+>` operator here :) If you just want to concatenate two `Text`, you can leverage their `Semigroup` instance and go with `<>` --> 

```
let endpoint = "api/v1/wallets?id=" <> fromWalletId (walletIds !! 0)
```

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        let endpoint = "api/v1/wallets?id=" <+> ( fromWalletId $ walletIds !! 0 )
Why are you actually defining those multiple walletIds actually ^^? The previous let binding feels superfluous, and this could just be:

```hs
let wId = (fixtures !! 0) ^. wallet . walletId
let endpoint = "api/v1/wallets?id=" <> fromWalletId wId
```

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        resp <- unsafeRequest ("GET", endpoint) $ Just $ [json|{}|]
If there's no body, you can just, not give any :p 

```hs
resp <- unsafeRequest ("GET", endpoint) Nothing
```

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        let endpoint = "api/v1/wallets?id=EQ%5B" <+> ( fromWalletId $ walletIds !! 0 ) <+> ("%5D" :: Text)
Arf :( .. I think might want to have those encoded brackets abstracted over some DSL combinator at some point. I think there's quite a few things that could be written in a nicer way with those pagination / filter / sort queries. 

I'll open a ticket to provide you with the necessary tools for that :+1:

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            forM_ ([3,6,6,9,0]) $ \coins -> do
So, as mentioned on slack, the last one here is a `0` coin. So, we can't expect the tx to be resolved at some point. It's a pity though that the backend doesn't reject the request in a first place.

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            forM_ ([3,6,6,9,0]) $ \coins -> do
Hence the failure.

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                     ]
Hmm.. To be totally fair, I'd have sorted them "by hand". Especially because both tests and the actual implementation are written in Haskell and probably uses the same sorting function under the hood. Therefore, if our `Ord` instance was messed up, this test would catch it because it would just reproduce what's the backend is also doing. 

Yet, that's somewhat tough because we don't know the wallet ids upfront :upside_down_face: Ids are generated deterministically from the wallet secret key, so it's still possible to force some mnemonics and compute their corresponding wallet ids upfront.

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                     ]
Same remark as before :)

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                        <+> "," <+> ( sortedWalletIds !! 2 )  <+> ("%5D" :: Text)
Why sorting the wallets by ids here? The sort given in the query is by `created_at` ?

2019-01-17 11:09 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +    fromWalletId (Client.WalletId a) = a
Looks like we could use a `Lens` here to unwrap things like this. This would play nicely with `fixture ^. wallet . walletId . asText` 

(not asking you to implement that, more like leaving a note for myself :p )

2019-01-17 12:13 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            forM_ ([3,6,6,9,0]) $ \coins -> do
OK, however, I have experienced the issue from #220 (also pretty much repeatedly) when I had no `0` coin with something like:
```
            forM_ (zip [1,2,3] [3,2,1]) $ \(name, coins) -> do
                setup $ defaultSetup
                    & walletName .~ show (name :: Int)
                    & initialCoins .~ [coins]
```

2019-01-17 12:22 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                        <+> "," <+> ( sortedWalletIds !! 2 )  <+> ("%5D" :: Text)
Yes. Sorting the ids because I want to use `RANGE[smallest, biggest]` and then I sort the results by `created_at` to make sure all the expected wallet id's are present in the returned results (because I know they will be presented in the descending order)...

2019-01-17 12:28 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                     ]
Not sure what you mean by sorting "by hand" :) Pls explain.

Also, I suppose `sort` is a _native_ Haskell method, so I trust it works fine. :)

2019-01-17 12:36 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        let endpoint = "api/v1/wallets?id=" <+> ( fromWalletId $ walletIds !! 0 )
>Why are you actually defining those multiple walletIds actually ^^?

Well, that's part of the test actually. Let's assume that filtering by id stopped working and returns all wallet's even if I specify particular one. If I have only one wallet in this test, it will not catch that :)

2019-01-21 09:39 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                     ]
Well, `sort` is native yes, but it relies on the `Ord` instance of type you're trying to sort. 

```hs
sort :: Ord a => [a] -> [a]
```

Therefore:

```hs
data WalletId = WalletId String deriving (Show, Eq)

instance Ord WalletId where
  (WalletId a) <= (WalletId b) = a >= b

main :: IO ()
main = do
  print $ sort $ [WalletId "a", WalletId "b", WalletId "c"]
  -- [WalletId "c",WalletId "b",WalletId "a"]
```

I suppose a comment would be enough here since we're _probably_ (I hope) using the stock `Ord` instance for the `WalletId` and that we aren't defining it by hand.

2019-01-22 16:20 UTC, KtorZ approved these changes

2019-01-22 16:21 UTC, merged

2019-01-24 12:18 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +                     ]
Ok, got it.
However I was not sorting `WalletId` but actually a `Text` since: `fromWalletId :: Client.WalletId -> Text`.

Maybe the name of the list should have been more descriptive then, like: `sortedWalletIdsText` instead of `sortedWalletIds`...

2019-01-24 12:21 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        let endpoint = "api/v1/wallets?id=" <+> ( fromWalletId $ walletIds !! 0 )
OK, read your code snippet now again, and... indeed, the additional `walletIds` list here is superfluous... :)