Make NodeStateAdaptor use the Node API
input-output-hk/cardano-wallet-legacy pull request #218
Opened 2019-01-11 14:51 UTC by Anviking

<p align="right">#87</p>

# Overview

- [ ] I have ...

# Comments

2019-01-18 16:36 UTC, Anviking commented on src/Cardano/Wallet/Action.hs
> +            Left  err -> error $ "Error talking to the Node: " <> (show err)
So this just crashes now…

2019-01-18 19:40 UTC, Anviking commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getTipSlotId             = eta $ API.unV1 . API.setSlotId <$> getNodeSettings client
Wait, why are we ever asking the node about the current `SlotId` if we know it ourselves in the wallet?

2019-01-21 09:29 UTC, KtorZ requested changes

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Action.hs
> +    params@(NewWalletBackendParams (WalletBackendParams{..}))
Good reminder that we need to get rid of this wrapper now :)

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Action.hs
> +         walletNodeTlsPrivKey
~This is already done as part of:~

https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Server/Plugins.hs#L96-L100

Ok, this was moved up there.

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Action.hs
>              genesisConfig
Minor styling advice: use qualified import to disambiguate ambiguous methods like `fromList` or `encode` which need contexts to get fully grasped when read. Here, it just makes think needlessly verbose: `newNodeStateAdaptor` is clear in itself :+1:

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Action.hs
> +            Left  err -> error $ "Error talking to the Node: " <> (show err)
Yeah... This is not a _valid_ use-case for `error`. Don't use raw exception for things that are actually expected to fail. We may use them seldom for invariants, but not as error handling. 

If there's no particular way to recover from a failure here, logging it would be the very least we could do :) 



Also `eta` doesn't strike me as an acronym for anything :thinking: ?

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getTipSlotId             = eta $ API.unV1 . API.setSlotId <$> getNodeSettings client
Do we ?

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getMaxTxSize             = eta $ fromIntegral . unMaxTxSize . API.setMaxTxSize <$> getNodeSettings client
I'd rather have this type be a `MaxTxSize` and carried as such.  This would remove the need for comments such as:

```hs
estimateMaxTxInputs
  :: Byte -- ^ Maximum size of a transaction
  -> Word64
estimateMaxTxInputs = estimateMaxTxInputsExplicitBounds
                        boundAddrAttrSize
                        boundTxAttrSize
```

We may unwrap it only when we truly need it!

2019-01-21 09:29 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
> +                    toTransaction wallet meta >>= \case
Any plan to update `toTransaction` in the future :no_mouth: ?

2019-01-21 09:51 UTC, Anviking commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getTipSlotId             = eta $ API.unV1 . API.setSlotId <$> getNodeSettings client
The only use-case:

https://github.com/input-output-hk/cardano-wallet/blob/8bbb1630bc903c230dc591cee182964e5119191e/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs#L100

2019-01-21 09:56 UTC, Anviking commented on src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
> +                    toTransaction wallet meta >>= \case
What do you mean?

2019-01-21 14:15 UTC, Anviking commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getMaxTxSize             = eta $ fromIntegral . unMaxTxSize . API.setMaxTxSize <$> getNodeSettings client
Hm. Ok. I think this looks inconsistent though:
```haskell
estimateMaxTxInputsExplicitBounds
  :: Byte -- ^ Size of @Attributes AddrAttributes@
  -> Byte -- ^ Size of @Attributes ()@
  -> MaxTxSize
```

And also, `MaxTxSize` is really uncomfortable to unwrap now since it is really the "intermediate API type" from the node API: 

```haskell
newtype MaxTxSize = MaxTxSize (MeasuredIn 'Bytes Word)
```

What about creating new newtypes in either:
1. `NodeStateAdaptor`
2. `API.V1.Types`
3. `Pos.Node.API` 

, like this:
```haskell
newtype MaxTxSize = MaxTxSize Byte
```
and convert between the two?

(For now irrelevant side note: don't we get into DerivingVia territory then? If we only use MeasuredIn for JSON instances…)

2019-01-21 15:03 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
> +                    toTransaction wallet meta >>= \case
Nevermind :upside_down_face:

2019-01-21 15:22 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getMaxTxSize             = eta $ fromIntegral . unMaxTxSize . API.setMaxTxSize <$> getNodeSettings client
> What about creating new newtypes

Sounds reasonable. But let's not bother too much for now :(  Perhaps a ticket with low-priority.

> don't we get into DerivingVia territory then

We could, but there's no problem that DerivingVia help us to solve here that generics can't already solve for us. Plus, we don't have DerivingVia in 8.4 :sob:

2019-01-21 15:24 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getTipSlotId             = eta $ API.unV1 . API.setSlotId <$> getNodeSettings client
What do you mean by "we know it ourselves" ?

2019-01-21 15:50 UTC, Anviking commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +    , getMaxTxSize             = eta $ fromIntegral . unMaxTxSize . API.setMaxTxSize <$> getNodeSettings client
>  But let's not bother too much for now

:+1::+1::+1:

Keeping the types in `NodeStateAdaptor` unchanged then, and creating a ticket for the future.

2019-01-22 15:51 UTC, Anviking commented on src/Cardano/Wallet/Action.hs
>              genesisConfig
Done. We get more cluttered imports though :(

2019-01-22 16:31 UTC, KtorZ approved these changes
LGTM.
Will merge after #237 (this also bumps cardano-sl, to latest develop).

2019-01-22 17:59 UTC, Anviking commented
> KtorZ approved these changes 

@KtorZ Though, FYI, when artificially failing in `toMonadIO` I was confused by seeing the following in the test output:

```
uncaught exception: IOException of type UserError
       user error (expected a successful response but got an error: ClientHttpError (ConnectionError "HttpExceptionRequest Request {\n  host                 = \"127.0.0.1\"\n  port                 = 8090\n  secure               = True\n  requestHeaders       = []\n  path                 = \"/api/internal/reset-wallet-state\"\n  queryString          = \"\"\n  method               = \"DELETE\"\n  proxy                = Nothing\n  rawBody              = False\n  redirectCount        = 10\n  responseTimeout      = ResponseTimeoutDefault\n  requestVersion       = HTTP/1.1\n}\n (InternalException (HostCannotConnect \"127.0.0.1\" [Network.Socket.connect: <socket: 101>: does not exist (Connection refused)]))"))
```

2019-01-22 23:32 UTC, Anviking commented on src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
> +newtype NodeCommunicationError = NodeCommunicationError String
Was a bit unsure about if we should have done `NodeCommunication e` instead and done buildable stuff

2019-01-24 11:23 UTC, merged