Denisshevchenko/32/hdrootid based on uniqueid
input-output-hk/cardano-wallet-legacy pull request #225
Opened 2019-01-15 21:11 UTC by denisshevchenko

<p align="right">#</p>

# Overview

- [ ] I have ...

# Comments

2019-01-16 07:32 UTC, denisshevchenko commented
@KtorZ Yes, I'm fixing it.

2019-01-17 08:33 UTC, denisshevchenko commented
All tests passed, Checks have failed because of Nix.

2019-01-17 10:42 UTC, KtorZ requested changes
Some changes in the `HdRootId` definitions thinking about what's coming next. 
Rest looks good :+1:

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +-- have to keep backward-compatibility for existing ids.
Sweet. 
Minor thing: when saying something is _bad_, it's better to explain _why_ because it may not be obvious to the reader.

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +        HdRootId "Ae2tdPwUPEZ18ZjTLnLVr9CEvUEUX4eW1LBHbxxxJgxdAYHrDeSCSbCxrvx"
This doesn't look very `Arbitrary` to me ;)

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +hdRootIdF = build
We don't need this. This is just `build`, so let's just rely on `build`. That's why type-classes are for in the end, they give you a common-interface between many types. Here, that's the `Buildable` interface.

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +                Right (_addr :: Core.Address) -> Right $ HdRootId rawId
Can't we leverage the `Alternative` abstraction here to make the code clearer in what it does :thinking: ? There's no need for a monadic approach here. We try one decoder or the other, in an alternative way.

`decodeHdRootId = decodeAddress <|> decodeUUID`

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    <$> nextRandom
We'll want to have that seeded (with an `EncryptedSecretKey`) which will also remove the need for `IO` here. Ideally, we want to parameterize it over the wallet's type (which isn't something we have now, but any `data WalletType = ExternallyOwned | FullyOwned` can do for now).

In one case, one wants to derive a "random" but deterministic UUID from it, in the other, derive an address from it. 
Therefore, I'll suggest to replace both this and `addressToHdRootId` with something more opaque: 

```hs
mkRandomHdRootId :: WalletType -> EncryptedSecretKey -> HdRootId
```

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> -                                               <*> pure mempty
This looked definitely more `Arbitrary` to me :p

2019-01-17 10:42 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/Sqlite.hs
> +    , _txMetaTableWalletId   :: Beam.Columnar f HdRootId
How does types get serialized to SQLite :thinking: ? It seems that anything that is `Typeable` can be serialized to the DB... Later, we do have those `FromField` instances that actually don't come from `beam` but come from another package `sqlite-simple`. So we use two diffferent sqlite driver o.O, that's fantastic. 

Anyway. If it works, it works; I'll comment on our `beam` rework ticket about it..

2019-01-18 07:44 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    <$> nextRandom
Ok, two questions:

1. Will we receive `EncryptedSecretKey` for EOS-wallets?
2. If so - how can we convert `EncryptedSecretKey` to `Int`? This is for "deterministically random` value of `UUID`: we need `Int`-value for `mkStdGen`.

2019-01-18 09:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    <$> nextRandom
Pffffiooou. I guess my mind wasn't really clear yesterday :no_mouth: ... We actually won't need to have deterministic generation of UUID for E.O. wallets because we won't need to peek into the keystore for them ANYWAY. 

Incidentally, obviously, we won't have any secret key for E.O. wallets (by definition). Discard my comment please and sorry about that.

2019-01-18 10:35 UTC, denisshevchenko commented
@KtorZ Fixed.

2019-01-18 13:02 UTC, KtorZ approved these changes
Wrapped up the remaining bits.

2019-01-18 13:08 UTC, denisshevchenko commented
@KtorZ You are awesome!

2019-01-18 13:56 UTC, merged

2019-01-18 14:13 UTC, akegalj reviewed
This is partial review - will finish it in few hours.

2019-01-18 14:13 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +-- | TODO: It is not very arbitrary, maybe we should improve it.
Lately I add all my TODO's as a development point to parrent issue like:
```
- [ ] Imrove Arbitrary instance of HdRootId
```

Later if I figure I am too lazy to work on that development point or find it less urgent I update the wording to: 
```
- [ ] Open an issue to improve Arbitrary instance of HdRootId
```

and I open a new ticket, mark the above development point as done.

That way its very visible how you can improve the parrent issue and usually I use this in my retrospective to list how we can improve things.

2019-01-18 14:13 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +        if isRight probablyUUID
Why not using alternative here:
```haskell
decodeUUID decodeBS <|> decodeAddress decodeBS
```
?

2019-01-18 14:13 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    . encToPublic $ esk
hm - there is a very small likelihood that `mkHdRootIdForEOWallet` and `mkHdRootIdForFOWallet` might collide, right ? Could `nextRandom` from `mkHdRootIdForEOWallet` produce already existing `HDRootId`  (using old `Core.Address`) ?

We enforce a rule in decoding `decodeHdRootId` by first trying EO id and later FO id but the result is dependant only on our ordering...

2019-01-18 14:17 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +-- | TODO: It is not very arbitrary, maybe we should improve it.
I see this has been fixed though https://github.com/input-output-hk/cardano-wallet/pull/225/commits/3ec6f10e6d83933eb54bcdc4bb1ae33f1e2f079a#diff-3c97127e54449021987ec2d29990f40dR54

2019-01-18 14:18 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +        if isRight probablyUUID
I see this has been fixed as well https://github.com/input-output-hk/cardano-wallet/pull/225/commits/3ec6f10e6d83933eb54bcdc4bb1ae33f1e2f079a#diff-3c97127e54449021987ec2d29990f40dR77

2019-01-18 14:18 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +        if isRight probablyUUID
Done already in https://github.com/input-output-hk/cardano-wallet/pull/225/commits/3ec6f10e6d83933eb54bcdc4bb1ae33f1e2f079a

Happy to see we concurred on that :)

2019-01-18 14:20 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    . encToPublic $ esk
There's a chance yes. But the same chance that we may generate two identical addresses from two different ESK I believe. This won't matter much since we enforce uniqueness of indexes in the DB. So, at the very least, we'll get an exception from the DB when trying to save a model with "duplicate" HdRootId.

2019-01-18 14:20 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    . encToPublic $ esk
`nextRandom` generates UUID v4, so it's not "very small likelihood", it's absolutely insignificant probability. :-)

2019-01-18 14:21 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +        if isRight probablyUUID
Already done.

2019-01-18 14:24 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdRootId.hs
> +    . encToPublic $ esk
:+1:

2019-01-18 19:16 UTC, akegalj reviewed
Finished review - the rest of PR looks good