Allow AddressPool to be created from an initial list of addresses
input-output-hk/cardano-wallet-legacy pull request #250
Opened 2019-01-23 19:42 UTC by KtorZ

<p align="right">#</p>

# Overview

- [x] I have extended the constructor of `AddressPool` to also accept an initial list of addresses + indexes
- [x] I have extended the test suite to reflect that change and tests the behavior when various initial (valid) list of addresses are given
- [x] I have provided an accessor to retrieve all known addresses from the pool gap (and allow future serialization / persistence of those addresses)

# Comments

This is for allowing serialization of the underlying pool. In theory,
we should never hit the 'Left' side of the constructor because given
addresses are generated only using the pool and nothing more.

2019-01-23 19:43 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +        :: Word32 -> Map address Word32
Moving to `Word32` to save us some `fromIntegral` here and there. Ideally, We could also just parameterize over `ix` which has `Num ix, Ord ix, Enum ix`, that should work the same.

2019-01-23 19:44 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +initAddressPool gap_ newAddress addrs0 = verifyPool $ AddressPool
So, we try to construct a pool from the given indexes, and, at the end, we verify that all indexes we keep track of are indeed sequential. We should never hit that `Left` side as long as we only extend pools using the address pool module. Yet, we never know.

2019-01-23 19:45 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    addresses_ = Map.fromList addrs0 <> nextAddresses_ (fromIntegral $ length addrs0)
So, to initialize the pool, we also always need to look ahead for some addresses (the next gap).

2019-01-23 19:46 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    in take (length xs - fromIntegral (pool ^. gap))  xs
Debatable. But if think it makes sense to only store addresses we have discovered up until now; that is, we have to remove `gap` addresses from the end.

2019-01-23 19:47 UTC, KtorZ commented on test/unit/Test/Spec/AddressPool.hs
> +        return $ InitialAddresses $ zip [0..n] [0..]
Nothing fancy here, we still model addresses with `Word32`, but we have to make sure they're unique. So, for generating valid list of addresses, we just take `n` unique natural numbers.

2019-01-24 07:53 UTC, uroboros requested changes

2019-01-24 07:53 UTC, uroboros commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    addresses_ = Map.fromList addrs0 <> nextAddresses_ (fromIntegral $ length addrs0)
`initAddressPool` is used when we create a new EOS wallet, in which case there are no initial addresses. I think this must remain unchanged and then we need a separate "create existing AddressPool", which uses the HdAddrs in AcidState for the given account, and creates a pool with purely those addrs. This way, if an addr is in AcidState, we consider it "known". In this way, the addr pool is only extended on "create new EOS with addr pool" and on BIP 44-style addr discovery

2019-01-24 07:53 UTC, uroboros commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    in take (length xs - fromIntegral (pool ^. gap))  xs
`getKnownAddrs` becomes trivial if we separate initAPool/readAPool (just the list of HdAddrs in AcidState for the given account)

2019-01-24 08:22 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    addresses_ = Map.fromList addrs0 <> nextAddresses_ (fromIntegral $ length addrs0)
Agreed. We can provide both constructors.

2019-01-24 08:26 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    in take (length xs - fromIntegral (pool ^. gap))  xs
That is only true provided we persist the list of undiscovered addresses. I was reluctant in doing so yesterday because we probably don't want undiscovered addresses in the DB.

On the other hand, we'll need to allow user to view addresses from the edge as their available addresses. And therefore, we might as well just persist that.

2019-01-24 08:33 UTC, uroboros commented on src/Cardano/Wallet/Kernel/AddressPool.hs
> +    in take (length xs - fromIntegral (pool ^. gap))  xs
keep in mind for HdRandom wallets, we persist undiscovered addrs (and mark them as "Used" when we actually discover)

2019-01-24 11:21 UTC, KtorZ commented
@uroboros ^^^

2019-01-24 11:32 UTC, uroboros approved these changes
I wonder about the naming of `emptyAPool` (which is not empty) vs `initAPool`. How about `newAPool` + `initAPool`?

2019-01-24 13:14 UTC, merged