[BIP44-239] (WIP) Extend prefiltering to EOS wallets for ApplyBlock
input-output-hk/cardano-wallet-legacy pull request #264
Opened 2019-01-28 09:22 UTC by uroboros

https://github.com/input-output-hk/cardano-wallet/issues/239

<p align="right">#</p>

# Overview

- [x] I have extended `prefilterBlocks` in the BListener to also prefilter for EOS wallets (this means that ApplyBlock will prefilter for EOS wallets as well)
- [x] I have extended newPending/newForeign prefiltering of tx outputs to deal with Eos wallet addresses
- [x] I have implemented restoreEosWallet and refactored the HdRnd restoreWallet (to enable sharing of code)

# TODO

- [ ] reconstruct EOS wallets/address pools  from Acidstate on wallet startup
- [ ] at entry point for Restoration, dispatch between Eos/HdRnd restorations
- [ ] remove `isOursSkip` from IsOurs class (try out Matt's idea for this)
- [ ] split Eos/Rnd wallet code more clearly (e.g. in Wallets.hs / Restore.hs)
- [ ] improve naming of Wallets.hs create* functions
- [ ] extend restoreKnownWallet and other restore* to EOS, where applicable

# Comments

- [ ] this is still WIP because I've not wired up the reading of EOS wallets from AcidState

2019-01-28 13:31 UTC, KtorZ requested changes

2019-01-28 13:31 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
I do not understand where this decision comes from :thinking: ? And I'd like us *not to* do or think about any optimizations until we have benchmarks and actual KPIs that allow us to:

- Justify the effort and complexity of developing an optimization
- Measure whether we are actually optimizing something 

First, let's make it work. Then, let's make it fast.

2019-01-28 13:31 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Read.hs
> +    nm = makeNetworkMagic pm
Ok. This is, I suppose, to avoid concurrency issues when accessing the snapshot multiple times throughout the life of a request call :thinking:  ?

2019-01-28 13:31 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +instance IsOurs (Map HdRootId Core.EncryptedSecretKey) where
Not sure to understand the rational here either :thinking: ? What's pushing for this change?

2019-01-28 13:42 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
to clarify, this was an existing optimisation that I _preserved_ in the more general case (skipping an isOurs computation for each Address even when there are no credentials)

2019-01-28 13:44 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Read.hs
> +    nm = makeNetworkMagic pm
at the main call sites of getWalletCredentials, we already have the snapshot

2019-01-28 13:44 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Read.hs
> +    nm = makeNetworkMagic pm
(we were doing a double getWalletSnapshot)

2019-01-28 13:48 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +instance IsOurs (Map HdRootId Core.EncryptedSecretKey) where
the IsOurs instance for EOS was using Map while IsOurs for ESK was using a list of tuples. Aligning these two made things more consistent (and semantically, the (Map RootId ESK) is more correct - it's a bag of wallets more than an (ordered) list

2019-01-28 13:57 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
I'd rather not have it here; it adds unnecessary complexity and only save us from one 

```hs
(,s) $ foldl' (<|>) Nothing $ Map.mapWithKey s
```
when `s` is `mempty`. This is okay and don't need any optimization :+1:

2019-01-28 14:04 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
no I can't do it inside isOurs (which is being called for each address) - I want a function to tell me that there are no wallets - this is non-trivial because of the abstract `s` in IsOurs - hence this added function to say "whatever my type, there are no wallets to prefilter". This is required for the significant optimisation if simply skipping processing any blocks of there are no wallets.

2019-01-28 14:05 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
having said that, there may be a better way to achieve that with just type annotations. However we do it, we need to know empty from not empty for the given "prefiltering state"

2019-01-28 14:16 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
I am not saying we should do anything inside the `isOurs` function. I am saying we should not anything at all. This optimization buys us nothing; The case where there's no wallet is a true edge-case we do not intend to optimize. If one uses the wallet, that's for keeping track of wallets! Otherwise, one's free to start a standard node :+1:

2019-01-28 14:29 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
IsOurs acts on a class of wallet (EO/FO) - since it's quite likely that one has only one class of wallets, say HdSeq, the other class(es) need to be trivially ignored

2019-01-28 14:30 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
(I'm saying it remains a necessary optimisation)

2019-01-28 17:44 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
I don't understand your point here. When we prefilter, we'll call the `isOurs` function for either some PublicKey + AddressPool, or for some HdRootId + SecretKey. Thus, we either have a E.O. wallet, or a F.O. one. There's no case where we'll call `isOurs` with... nothing to call it with in a first place. Otherwise, something should be fixed at the caller site, not here in this function.

We could even constraint the state to be a non empty list of credentials because conceptually, that's what it is.

2019-01-30 18:09 UTC, parsonsmatt requested changes

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/BListener.hs
> +-- (e.g. writing into the acid-state DB log) by skipping such block application).
This comment should be part of the Haddock comment over the function declaration -- we don't really have haddocks now, but it'd be good to not obstruct that as much as possible.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/BListener.hs
> +        listToMaybe' l = if null l then Nothing else (Just l)
This is also `Data.List.NonEmpty.nonEmpty`, but that preserves the invariant that the list is non-empty.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    -- For the given state, check whether an address is "ours"
We can tag these comments as Haddocsk with the `-- |` syntax, then they could show up whenever we render docs or with the `:doc` GHCi command.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/Pending.hs
> +{-# LANGUAGE LambdaCase #-}
needs a `stylish-haskell` run

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
I don't believe this is a necessary *class* method -- we can replace it with direct calls in the implementations.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOurs _ s@(isOursSkip -> True) = (Nothing, s)
eg, we use `isOursSkip` here -- but we could just use `Map.null` directly and not add a class member.

In the case of an empty `Map`, `flip Map.mapWithKey` is a noop, as is `foldl' (<|>) Nothing`. I think that this optimization isn't warranted.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/Pending.hs
>          allOurs
so this type sig was generalized to work with `IsOurs s`, so we can use it over two different kinds of `Map`. Would it possibly make sense to change the type class definition to the following?

```haskell
class IsOurs k v | k -> v, v -> k where
  isOurs :: Core.Addres -> Map k v -> (Maybe HdAddress, Map k v)
```

That allows us to define

```haskell
isOursSkip :: IsOurs k v => Map k v -> Bool
isOursSkip = Map.null
```

and recover the optimization without polluting the class with extraneous `Foldable`-like methods. The only instances are the ones defined in this PR, and both share a similar state.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/Pending.hs
>          allOurs
Alternatively, `class IsOurs db a | db -> a, a -> db where isOurs :: Core.Address -> db a -> ...`, which lets us vary the database type, and we can then require a `Foldable db` instance to give us `null :: Foldable f => f a -> Bool`.

2019-01-30 18:09 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/Read.hs
> +    = return Map.empty
Is this going to be done as part of this PR?

2019-01-31 11:54 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOursSkip :: s -> Bool
I was driven to the need for the "is empty state" predicate because at the call sites I mostly want to call it for multiple state types, and then just merge the results (your suggestion below solves this nicely)

2019-01-31 11:56 UTC, uroboros commented on src/Cardano/Wallet/Kernel/BListener.hs
> +-- (e.g. writing into the acid-state DB log) by skipping such block application).
👍

2019-01-31 12:06 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Pending.hs
>          allOurs
that's clever, I'll try that! The `IsOurs k v` is probably too closely tied to Map for our purposes, but `IsOurs db a` seems just what I need to get at that Foldable constraint.

2019-01-31 12:08 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Read.hs
> +    = return Map.empty
yes, that's waiting for another PR to be merged first

2019-02-05 16:14 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/BListener.hs
> +        listToMaybe' l = if null l then Nothing else (Just l)
Maybe like this?

```
listToMaybe' :: [PrefilterResult] -> Maybe [PrefilterResult]
listToMaybe' [] = Nothing
listToMaybe' l = Just l
```

2019-02-05 16:18 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Pending.hs
> +        fullPref
IMHO it's not a good name. Why not `fullPrefilter`?

2019-02-06 10:20 UTC, KtorZ requested changes

2019-02-06 10:20 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Pending.hs
> +                -- it as either type (one of which will be trivial)
This is not _true_. We do know the `HdAccountId`, so we are one call away from knowing the corresponding `HdAccount` and its kind. That'll greatly simplify the code below.

2019-02-06 10:20 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Restore.hs
> +restoreHdWallet pw prefContext createWallet_ restoreWallet_
I didn't quite review any of the above _yet_ ^^^ , because I thought this PR and task was about prefiltering. I'd recommend we first figure out how to do prefiltering correctly and finalize the other bits before we move on to restoration...

2019-02-06 10:20 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +        val = maybe def id (Map.lookup accId utxos)
Same here. Let's move with incremental steps. And test the things we add as we add them.

2019-02-07 11:48 UTC, uroboros commented
Will introduce this work in a series of PRs, closing this now

2019-02-07 11:49 UTC, closed without merging