Add error support when not enough utxo is met upon multioutput …
input-output-hk/cardano-wallet-legacy pull request #272
Opened 2019-01-29 14:13 UTC by paweljakubas

#190 

<p align="right">#</p>

# Overview

- [x] Integration test illustrating the following scenarios were added:
- [x] A multi-output transaction fails because there's not enough UTxO to cover for all outputs
- [x] A multi-output transaction succeeds
- [x] The API returns a more meaningful error when the case for (failing) multi-output is encountered, suggesting the user to have a look at /api/v1/wallets/{walletId}/statistics/utxo

# Comments

2019-01-29 14:27 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +            ]
API errors are kinda... complicated at the moment but we do want to derive most things generically. I'd suggest to have:

```hs
data ErrUtxoNotEnoughFragmented = ErrUtxoNotEnoughFragmented
    { missingUtxos :: Int
    , msg :: Text
    }
```

And, provide a corresponding message as text in the `ReifyError`. This way, we can simply derive the ToJSON and FromJSON instance generically and don't need this manual wiring.

Then, make `details` the `diagnosticKey` such that it will generate a corresponding JSEnd error.

2019-01-29 14:35 UTC, KtorZ requested changes

2019-01-29 14:35 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Transactions.hs
> +           determineCorrectUtxoFragmentation payees availableUtxo
I'll suggest to change the signature of `determineCorrectUxoFragmentation` to `checkUtxoFragmentation :: NonEmpty (Address, Coin) -> Utxo -> Either NumberOfMissingUtxos ()` 

There's no need to return something here and the check is really just about stopping the computation or, moving forward.

2019-01-29 14:35 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +                      CreateWallet
Please use the fixture for that. Fixture is used to create an initial wallet without the hassle of generating all the bits yourself. Wallets come default accounts `defaultAccountId` that you can use in the scenario. So basically, the lines above can just be replaced with:

```hs
fixture01 <- setup $ defaultSetup & name .~ "newWallet1"
```

2019-01-29 14:35 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +                    $- wallet2 ^. walletId
Same as above :+1:

2019-01-29 14:35 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +                (map (\coin -> Client.WalletCoin $ mkCoin coin) [10,11])
We really want to keep the complexity and the internal logic outside of the scenario. The `DSL` already offers:

```hs
defaultDistribution
    :: HasType (NonEmpty Address) s
    => Word64
    -> s
    -> NonEmpty PaymentDistribution
```

which isn't enough in your case, so I'd suggest to add a new:

```hs
customDistribution
    :: NonEmpty (Address, Word64)
    -> NonEmpty PaymentDistribution
```

2019-01-29 14:35 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            , expectTxStatusEventually [Creating, Applying, InNewestBlocks, Persisted]
I'd rather wait for `InNewestBlocks` here, to make sure the transaction is actually indeed accepted by the nodes.

2019-01-30 12:20 UTC, paweljakubas commented on src/Cardano/Wallet/API/V1/Types.hs
> +            ]
done

2019-01-30 12:20 UTC, paweljakubas commented on src/Cardano/Wallet/Kernel/Transactions.hs
> +           determineCorrectUtxoFragmentation payees availableUtxo
done

2019-01-30 12:21 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +                      CreateWallet
applied. now it is much easier to read and all imp delegated to DSL

2019-01-30 12:21 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +                    $- wallet2 ^. walletId
:+1:

2019-01-30 12:21 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +                (map (\coin -> Client.WalletCoin $ mkCoin coin) [10,11])
done

2019-01-30 12:21 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            , expectTxStatusEventually [Creating, Applying, InNewestBlocks, Persisted]
indeed -> done

2019-01-30 13:50 UTC, KtorZ requested changes

2019-01-30 13:50 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +            bprint ("Missing "%build%" utxos to accommodate all outputs of the transaction") missingUtxos
Nice effort :smile: 
Pro tip: an `(s)` works marvelously for this kind of things:

```hs
             bprint ("Missing "%build%" utxo(s) to accommodate all outputs of the transaction") missingUtxos 
```

And, in general, as a backend, the accuracy of your grammar on edge-cases is really your last concern ^^"

2019-01-30 13:50 UTC, KtorZ commented on test/unit/Servant/JsendCompliance.hs
> +                     (===))
Minor remark: when you fix something like this (which has nothing to do with our PR per se), make it a separate commit. Such that, the history is clearer to understand and, commits can be cherry-picked / reverted easily when they need to. 

Thanks for fixing the warning though :+1:

2019-01-30 13:50 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            [ expectWalletError (UtxoNotEnoughFragmented (Client.ErrUtxoNotEnoughFragmented 1 Client.msgUtxoNotEnoughFragmented))
:+1: Note that, this is a small "breaking" change and we should notify the frontend folks about this!

2019-01-30 13:50 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +            "msg"
Note, by using "msg" as a diagnostic key, we'll end up with an error like:

```json
{    
    "status": "error", 
    "diagnostic": {        
        "msg": {            
            "msg": "...",            
            "missingUtxos": 14        
        }    
    },    
    "message": "UtxoNotEnoughFragmented"
}
```

So that's quite a lot of 'msg / messages' ... May I recommand to change the diagnostic key to `details` and maybe also, to change the `theMsg` by `theHelp` in the `ErrUtxoNotEnoughFragmented` type ? This will generate something more like:

```json
{    
    "status": "error", 
    "diagnostic": {        
        "details": {            
            "help": "...",            
            "missingUtxos": 14        
        }    
    },    
    "message": "UtxoNotEnoughFragmented"
}
```

2019-01-30 13:50 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +                                $ concatMap (\acc -> acc ^. addresses)
NOTE: `\x -> x ^. myLens === view myLens`, favor functions over operator when passing functions around :+1:

2019-01-30 13:50 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +       zipWith PaymentDistribution recepientWalAddresses (map (\coin -> WalletCoin $ mkCoin coin) coins)
This may lead to unexpected results if:

- The `accounts` and `coins` list don't have the same number of elements
- The `accounts` have more than one address 

I'd recommend to either check that as invariant and fail hard if the invariant aren't met, or (better IMO), require the caller to provide the a `(Account, Word64)]` himself and only take the first address of each account -- failing if there's none maybe. Or asking directly for `[(Address, Word64)]`

2019-01-30 13:50 UTC, KtorZ commented on test/unit/Servant/JsendCompliance.hs
> +                     (===))
Also, this happens because `-WError` isn't on in `cardano-wallet.cabal` for the unit tests. So I'd rather turn it on as well while we're at it :)

2019-01-30 15:10 UTC, paweljakubas commented on src/Cardano/Wallet/API/V1/Types.hs
> +            bprint ("Missing "%build%" utxos to accommodate all outputs of the transaction") missingUtxos
yeah, a little bit overstretched here :-) corrected

2019-01-30 15:11 UTC, paweljakubas commented on test/unit/Servant/JsendCompliance.hs
> +                     (===))
reverted the change, and included in another commit (together with switching on of -Werror flag for unit tests)

2019-01-30 15:11 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            [ expectWalletError (UtxoNotEnoughFragmented (Client.ErrUtxoNotEnoughFragmented 1 Client.msgUtxoNotEnoughFragmented))
Will inform Nicola team about the change

2019-01-30 15:11 UTC, paweljakubas commented on src/Cardano/Wallet/API/V1/Types.hs
> +            "msg"
done

2019-01-30 15:12 UTC, paweljakubas commented on test/integration/Test/Integration/Framework/DSL.hs
> +                                $ concatMap (\acc -> acc ^. addresses)
yes, used `view` instead

2019-01-30 15:12 UTC, paweljakubas commented on test/integration/Test/Integration/Framework/DSL.hs
> +       zipWith PaymentDistribution recepientWalAddresses (map (\coin -> WalletCoin $ mkCoin coin) coins)
done

2019-01-30 17:05 UTC, KtorZ approved these changes

2019-01-30 17:06 UTC, merged

2019-01-30 17:15 UTC, KtorZ commented
Nice work @paweljakubas! Thanks. Don't forget to put your ticket in QA after giving a few pointers to @piotr-iohk!