getAddressPool function.
input-output-hk/cardano-wallet-legacy pull request #273
Opened 2019-01-29 14:24 UTC by denisshevchenko

<p align="right">#231</p>

# Overview

- [ ] I have ...

# Comments

2019-01-29 14:26 UTC, uroboros approved these changes
LGTM

2019-01-29 15:43 UTC, KtorZ requested changes
Not sure what you're trying to achieve here :thinking: ?

2019-01-29 15:43 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
We are loosing the benefits of having two branches for `HdAccount` if we start doing things like this. The caller should be pattern matching here and only creates an address pool when it makes sense.

2019-01-30 05:05 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
Hm... We can create `emptyAddressPool` only for `HdAccount` with EO-branch, right?

2019-02-01 15:26 UTC, KtorZ commented
So in the end, what was the need for this function again :thinking: ?

2019-02-01 15:28 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
@KtorZ the function has a confusing name - it is meant for create a fresh pool for a new account (with the first gap of addresses)

2019-02-01 15:31 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
I can rename it. For example, `createAddressPool` or `createEmptyAddressPool`.

2019-02-01 15:34 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
I think stay away from "empty" (it's not) - preferable something like initAddressPool, but that name is already taken. Maybe we should rename that rather? (mkAddressPool?)

2019-02-01 15:55 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
Though the problem is more than the name here. That function _shouldn't_ take a full `HdAccount` because it has nothing to do with F.O. accounts :+1:

2019-02-01 15:59 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
We assume that this function will be used _only_ with EO-accounts. But if not - it will return `Nothing`.

Another way - pass `HdAccountBase` instead of `HdAccount`.

2019-02-01 16:26 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
Another way - pass only things we really need.

2019-02-01 16:26 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
I mean 

```
getAddressPool
    :: (Core.PublicKey -> Core.Address)
    -> Core.PublicKey
    -> AddressPoolGap
    -> AddressPool Core.Address
```

2019-02-01 16:28 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +getAddressPool mkAddress (HdAccount (HdAccountBaseEO _ accPK gap) _ _ _) =
> Another way - pass only things we really need.

YES ! Don't assume things. Don't trust that "we" or even you will use the function in a "correct way", make it so! If there's only one way to use a function, and that's the good way, then you don't have to assume anything.

2019-02-01 17:09 UTC, denisshevchenko commented
> what was the need for this function again thinking ?

@uroboros ? :-)

2019-02-01 17:13 UTC, uroboros commented
@denisshevchenko when we create EOS wallets, we should use that function to compute the first pool of  HdAddreses, which we should persist on create. When I do prefiltering, I'll read from Acidstate and reconstruct pools using the "create existing pool" function

2019-02-01 17:17 UTC, uroboros commented
@denisshevchenko having said that... in create EOS wallets, when we create the pool of addrs for each new EOS account, we only need the `nextAddresses` function, so we _could_ lose "what used to be called emptyAddrPool". We need the other one though

2019-02-01 21:08 UTC, KtorZ approved these changes

2019-02-01 21:08 UTC, merged