Denisshevchenko/36/eos wallets rdl
input-output-hk/cardano-wallet-legacy pull request #278
Opened 2019-01-30 08:13 UTC by denisshevchenko

<p align="right">#36</p>

# Overview

- [ ] I have added `Read`-operation for EOS-wallets.
- [ ] I have added `Delete`-operation for EOS-wallets.
- [ ] I have added `List`-operation for EOS-wallets.

# Comments

2019-01-30 08:18 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    , eoswalAddressPoolGap = error "TODO, we have to take it from one of accounts, will be done later, see issue #36"
We store address pool gap in `HdAccount`s, not in `HdRoot`, so we must take any of corresponding accounts and take gap from it. It will be done later.

2019-01-30 08:20 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer.hs
> -
I thought that we can use the same `DeleteWalletError`, because we actually delete the same `HdRoot` as for EO-wallets.

2019-01-30 09:04 UTC, akegalj approved these changes
I just skimmed through it but it looks good to me

2019-01-30 09:18 UTC, KtorZ requested changes

2019-01-30 09:18 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    walletId   = sformat build rootId
I'd rather not have that function. Having some similar where clauses in both `toEosWallet` and `toWallet` is fine...

2019-01-30 09:18 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    , eoswalAddressPoolGap = error "TODO, we have to take it from one of accounts, will be done later, see issue #36"
What about doing it as part of this PR :) ?

2019-01-30 09:21 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    walletId   = sformat build rootId
`hlint` is angry in this case (Duplication). :-)

2019-01-30 10:09 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    walletId   = sformat build rootId
Well, that wouldn't be the first case `hlint` suggests something wrong :upside_down_face:

2019-01-30 10:10 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    walletId   = sformat build rootId
Unless you truly think and argue that this makes the code looks better ...

2019-01-30 10:13 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    walletId   = sformat build rootId
So we've reduce duplication to avoid having to modify code in two different places. But now, we'd have to modify it in 3 different places. Not sure what we've improved here to be honest. 

In order to really remove duplication, we could have provided a different `toWallet` function that may just construct the first part common part of an `EosWallet` or `Wallet` and leave the rest to the caller... But to be honest, this complexifies the whole for close to no value. 

So yes, I am arguably saying that `hlint` can go to hell here :)

2019-01-30 12:35 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +    , eoswalAddressPoolGap = error "TODO, we have to take it from one of accounts, will be done later, see issue #36"
@KtorZ Done (please see last commit).

2019-02-01 10:50 UTC, KtorZ requested changes

2019-02-01 10:50 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    (firstAccount:_) = IxSet.toList accountSet
Hmm. This feels wrong and may eventually bite us. 
We should:

- Forbid empty E.O. wallets creation (not in this PR, but I'll add a bullet point to #236)
- Make sure that all accounts have a same gap within a wallet
- Return an error here if there's no account

2019-02-01 10:50 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +                                     . to HD.getWalletName
Please, no more variable-length indent :pray:

2019-02-01 10:50 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
> +-- sections, but this is not a problem.
This doesn't really explain _why_ it's not a problem :/ ..

2019-02-01 12:36 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    (firstAccount:_) = IxSet.toList accountSet
> Make sure that all accounts have a same gap within a wallet

Of course they have the same gap, because they was _created_ from the same gap (during EOS-wallet creation).

2019-02-01 12:55 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    (firstAccount:_) = IxSet.toList accountSet
> Of course they have the same gap,

They **ought to** have the same gap. But there's nothing that can be checked at compile-time that guarantees this invariant. Hence the need for checking it and, throwing an exception if it doesn't hold. 

>  In this case we just return default value of gap.

No, that's the point. If there's no accounts, that's an error! This shouldn't happen and we should enforce that via the API. If it ever happens, that's a bug / fault in our implementation

2019-02-04 10:51 UTC, denisshevchenko commented
@KtorZ I've added checks for `HdAccount`s in EOS-wallets, with corresponding errors.

2019-02-04 11:38 UTC, KtorZ requested changes

2019-02-04 11:38 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/ReifyWalletError.hs
> +        V1.UnknownError (sformat build ex)
This is a new feature, so we have some freedom here in what errors we define. There's actually no particular need to reify anything here and we could have a 1:1 mapping between those errors and new API errors. 

As a reminder, those API errors are so far, our only debugging tools when somethings goes wrong on the wallet of our users and for them, that's the only feedback they get from the API. So, returning `UnknownError` shouldn't only happen in exceptional situation (read this as: never, if possible).

2019-02-04 12:34 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/ReifyWalletError.hs
> +        V1.UnknownError (sformat build ex)
Thanks, fixed.

2019-02-04 13:23 UTC, KtorZ requested changes

2019-02-04 13:23 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +addressPoolGapByRootId rootId db = do
So ideally, this would return a specific error as well. Truth is that the branches below of `GetEosWalletError` are only met within this function. And, other branches can never be met by this function.
So, saying that this function can return a `WalletIdDecodingFailed` is a bit of a lie :sweat_smile: ...

2019-02-04 13:23 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +        else Right $ IxSet.fromList eosWallets
A case reads better for this kind of manipulation :+1:

2019-02-04 13:23 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    let (errors, eosWallets) = partitionEithers result
We aren't quite leveraging the applicative aspect of `Either` and `ExceptT` here. Especially if we just intend to stop at the first error, we could instead `traverse` the list of hd roots and end up with a `Either Error [EosWallet]`

2019-02-04 14:56 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +addressPoolGapByRootId rootId db = do
Done.

2019-02-04 15:05 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +        else Right $ IxSet.fromList eosWallets
You're right! Fixed.

2019-02-04 16:56 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    let (errors, eosWallets) = partitionEithers result
Done.

2019-02-04 19:18 UTC, denisshevchenko commented
@KtorZ All checks have passed (`hlint` is happy again).

2019-02-05 11:17 UTC, KtorZ approved these changes

2019-02-05 11:17 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    let result = traverse (\root -> either Left (Right . toEosWallet db root) $
Note that:

```hs
\root -> either Left (Right . toEosWallet db root)
````

can be written more idiomatically as:

```
fmap (toEosWallet db)
```

2019-02-05 11:17 UTC, merged