Update operation, for EOS-wallets.
input-output-hk/cardano-wallet-legacy pull request #304
Opened 2019-02-05 11:34 UTC by denisshevchenko

<p align="right">#36</p>

# Overview

- [ ] I have added `Update`-operation for EOS-wallets. It allows to update name, assurance level and address pool gap.

# Comments

2019-02-05 14:18 UTC, uroboros reviewed
mostly LGTM

2019-02-05 14:18 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Accounts.hs
> +    return $ case res of
`return res` ? ;)

2019-02-05 14:18 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    setHdAccountGap :: HdAccountBase -> AddressPoolGap -> HdAccountBase
more lens here?

`setHdAccountGap base@(HdAccountBaseEO _ _ _) newGap = base ^. hdAccountBaseEOAddressPoolGap .~ newGap`

`setHdAccountGap base _ = base`

2019-02-05 14:21 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Accounts.hs
> +    return $ case res of
Ops. :-) You're right!

2019-02-06 11:13 UTC, KtorZ requested changes

2019-02-06 11:13 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +        modifyAndGetNew $ hdAccountBaseGap .~ gap
I'd actually be more in favor of a loud and explicit failure in case we attempt to update the gap of an HdAccount that doesn't refer to an externally owned account. We don't want to be silently swallowing this but report the failure as early as possible.

Similarly, we _should_ probably not want a lens like `hdAccountBaseGap` precisely because, it's in essence, a partial function we just happen to default in the case of the FO branch. It does make sense to define a lens like `hdRootId` because this exists on both branch, but for something like the gap, we definitely want to pattern match and fail in case we happen to be on the wrong branch.

2019-02-06 11:13 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +        return $ Kernel.accountsByRootId db rootId
So, I had this feeling today when writing the integration tests for the externally owned wallet and I believe we should hand-over to the DB layer the invariant checks on the eos accounts to make sure that, whatever we get from the db is actually valid data. And similarly, we want to check that whatever we put in the db is valid all-the-same.

2019-02-06 11:13 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +        return $ Kernel.accountsByRootId db rootId
I'll actually work on that and provide a PR ASAP.

2019-02-07 09:16 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +                throwError $ UnknownHdAccount accId
This is rather misleading as an error because, the account actually exists. The problem is that it's not what we expected it to be. Imagine debugging this, we see an error `UnknownHdAccount` and start trying to figure out why this account doesn't exist despite having created it before. 
What we really want here is a clear signal that, we are trying to perform an invalid operation on a fully owned account.

2019-02-07 09:17 UTC, KtorZ requested changes

2019-02-07 09:17 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +-- import qualified Cardano.Wallet.Kernel.DB.HdWallet.Read as HD
Why is this commented out :thinking: ? Why not remove it entirely ?

2019-02-07 09:21 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +                throwError $ UnknownHdAccount accId
Yes, this is just a first code that compiles. :-)

2019-02-07 09:22 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +-- import qualified Cardano.Wallet.Kernel.DB.HdWallet.Read as HD
Ops, forgot.. Removed.

2019-02-07 10:09 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +                throwError $ UnknownHdAccount accId
@KtorZ What is the best solution here: add new error in `UnknownHdAccount` type, or introduce new error type?

2019-02-07 10:10 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +                throwError $ UnknownHdAccount accId
You tell me :)?

2019-02-07 10:50 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +                throwError $ UnknownHdAccount accId
Done.

2019-02-07 11:36 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
> +        modifyAndGetNew $ hdAccountBaseGap .~ gap
Done.

2019-02-07 15:37 UTC, KtorZ approved these changes

2019-02-07 15:38 UTC, merged