258 manual testing
input-output-hk/cardano-wallet-legacy pull request #308
Opened 2019-02-05 14:16 UTC by piotr-iohk

<p align="right">#</p>

# Overview

- [ ] I have added manual testing procedures for #258. The procedures include batch import of addresses while wallet is restoring and importing large number of addresses.
- [ ] I have added simple helper bash scripts to facilitate generating large number of addresses and building `curl` request for doing batch import of those addresses 

# Comments

2019-02-05 14:18 UTC, piotr-iohk commented on .gitignore
> +state-staging
I have added this as the recently updated procedure of starting a node with cardano-wallet creates `state-staging` directory. (https://github.com/input-output-hk/cardano-wallet/wiki/Building-Running-and-Testing-a-wallet-node)

2019-02-06 11:11 UTC, KtorZ requested changes

2019-02-06 11:11 UTC, KtorZ commented on test/manual/258/scenarios.md
> + - Have a Daedalus staging installed and synced. Get Daedalus staging from https://buildkite.com/input-output-hk/daedalus.
As discussed, I'd suggest we _don't_ refer to Daedalus here as this can be achieved with a mere wallet server already.

2019-02-06 11:11 UTC, KtorZ commented on test/manual/258/scenarios.md
> +3. `["offer","need","accuse","yellow","sibling","robust","view","rare","cry","picture", "weather", "love"]` - `Ae2tdPwUPEZLXCZQkmwcatABSc5Fw1bp3dk5nBkNnkNHy6teLdxqQm8NPgW`
Are we confident about making those publicly available? I hope so, because now they are :no_mouth:

2019-02-06 14:36 UTC, piotr-iohk commented on test/manual/258/scenarios.md
> + - Have a Daedalus staging installed and synced. Get Daedalus staging from https://buildkite.com/input-output-hk/daedalus.
:+1:

2019-02-06 14:45 UTC, piotr-iohk commented on test/manual/258/scenarios.md
> +3. `["offer","need","accuse","yellow","sibling","robust","view","rare","cry","picture", "weather", "love"]` - `Ae2tdPwUPEZLXCZQkmwcatABSc5Fw1bp3dk5nBkNnkNHy6teLdxqQm8NPgW`
Yes. However, I have removed them after all while rewritting scenarios to be in the context of wallet backend only.

2019-02-06 14:50 UTC, piotr-iohk commented on test/manual/scripts/generate-addresses.sh
> +#   -c --client=FILEPATH     TLS client certificate expected by the server [default: ../../../state-staging/tls/client/client.pem]
I have changed default TLS client path to be in-line with https://github.com/input-output-hk/cardano-wallet/wiki/Building-Running-and-Testing-a-wallet-node, as most likely scenario for those scripts to be used IMHO would be when you start a node using that particular guide.

2019-02-07 08:11 UTC, KtorZ commented on test/manual/scripts/wallet.sh
> +#	wallet (create | restore) [options] MNEMONICS...
sweet :open_mouth:

2019-02-07 08:12 UTC, KtorZ approved these changes

2019-02-07 08:17 UTC, merged