[220] Add NewTransactionZeroAmountCoin
input-output-hk/cardano-wallet-legacy pull request #318
Opened 2019-02-06 15:07 UTC by paweljakubas

[220] Finishing error

<p align="right">#220</p>

# Overview

- [x] I have added ZeroAmountOutput error together with tests

# Comments

It was seen that one cannot construct transactions with zero amount output as  in the current version it can incur long response times. The decision was to forbid it on the level of wallet by introduction of respective error. When it will be supported underneath it can be revoked though (eg. during Shelley era)

2019-02-07 08:17 UTC, KtorZ approved these changes

2019-02-07 08:17 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Swagger.hs
> +If anyone is set to zero (also in single recipient transaction) a `ZeroAmountCoin` error is triggered.
I'd only go for the first sentence here.

2019-02-07 08:33 UTC, paweljakubas commented on src/Cardano/Wallet/API/V1/Swagger.hs
> +If anyone is set to zero (also in single recipient transaction) a `ZeroAmountCoin` error is triggered.
deleted second sentenced and squashed

2019-02-07 09:57 UTC, KtorZ commented
Actually. Why don't we even fix that at the API-level as-well ? 

https://input-output-hk.github.io/cardano-wallet/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions%2Fpost

I mean, here, if we make sure that the amount can't be negative or null then we even prevent such transactions from making it into the kernel.

2019-02-07 09:59 UTC, KtorZ requested changes

2019-02-07 09:59 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +            err403
Also, just noticed that. This should be a `400`. `403` is usually reserved for lack of permissions on an authenticated client. 
Likely, our API will never return a 403 because we don't have any particular notion of access control layer (ACL) on our API.

2019-02-07 13:50 UTC, paweljakubas commented on src/Cardano/Wallet/API/V1/Types.hs
>              err403
shouldn't here also be 400 instead of 403 ?

2019-02-07 13:54 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
> +        withExceptT NewTransactionZeroAmountCoinsDetected $ exceptT $ checkCoins payees
I added here also API support to check against zero amount coins. Here, however when we use `pstUnsignedTransaction` we will end up with  `UnknownError "NewUnsignedTransactionError"` as these errors are not exposed up in **ReifyWalletError**

Moreover, we can also add catching these same error in `estimateFees`. Right now it bases on : 
```
data EstimateFeesError = EstFeesTxCreationFailed NewTransactionError
```

2019-02-07 14:12 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
>              err403
For a lack of better error code, no, I believe this one is okay here.

2019-02-07 14:36 UTC, paweljakubas commented on test/integration/Test/Integration/Scenario/Transactions.hs
> +            [ expectWalletError ( ZeroAmountCoin (Client.ErrZeroAmountCoin 1 Client.msgZeroAmountCoin))
Here, is the the proof that `getTransactionFee` embraces wallet errors. But to do it it calls Kernel stuff. Which is in contrast to what happens when `postTransaction` or `postUnsignedTransaction` is called (though in the latter case it is not welcomed on the wallet errors board)

2019-02-07 14:46 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
> +        withExceptT NewTransactionZeroAmountCoinsDetected $ exceptT $ checkCoins payees
Hmm. That's not what I meant; here we are basically doing two times the same check but at different places. 
I meant that, instead of having a wallet coin amount here (https://github.com/input-output-hk/cardano-wallet/blob/b7dcca7a061e1fffe1ef86bd7a017e67daa14ceb/src/Cardano/Wallet/API/V1/Types.hs#L277-L301) ranging from 0 (included) to max coin value, it could range from 1 to max coin value.

Let's not bother with that now actually. We have more important stuff to deal with.

2019-02-08 09:30 UTC, KtorZ requested changes

2019-02-08 09:30 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
> +           Right ()
This is duplicated with the above. We don't need to double-check that, or if we do, let's re-use functions and not duplicate them.

2019-02-08 09:53 UTC, paweljakubas commented on src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
> +           Right ()
So I opted for avoiding duplication. Just relying only on Kernel level checks and removing WalletLayer ones

2019-02-08 10:36 UTC, KtorZ approved these changes

2019-02-08 10:36 UTC, merged