[BIP44-239] Prepare to extend prefiltering to EOS wallets for ApplyBlock
input-output-hk/cardano-wallet-legacy pull request #321
Opened 2019-02-07 11:57 UTC by uroboros

https://github.com/input-output-hk/cardano-wallet/issues/239

<p align="right">#</p>

# Overview

- [x] I have prepared `prefilterBlocks` in the BListener to also prefilter for EOS wallets during ApplyBlock
- [x] I have changed the IsOurs class to `class IsOurs k v` so that I can constrain the container of the prefiltering context to a Map (which gives us a way to check for empty prefiltering context)
- [x] I've changed `getWalletCredentials` to accept a snapshot instead of PassiveWallet (since the snapshot is already available at the call sites and this prevents a double getSnapshot)

# Comments

This PR simply abstracts the prefiltering mechanism - at this stage the BListener still just gets the HdRnd wallets from the Keystore and does HdRnd prefiltering on those wallets.

Next up is to include getEosWallets.

2019-02-07 14:38 UTC, KtorZ requested changes

2019-02-07 14:38 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOurs _ s@(Map.null -> True) = (Nothing, s)
This is really not necessary :relaxed: ... That's exactly what happens when folding on an empty map, and this doesn't really save us from any computation :+1:

2019-02-07 14:38 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/BListener.hs
> -                             <> "a different number of elements than the input ones."
Why are we getting rid of the invariant here?

2019-02-07 14:38 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOurs :: Core.Address -> Map k v -> (Maybe HdAddress, Map k v)
I don't get the need for this change to be honest. I believe it comes after Matt's comment on the previous PR (https://github.com/input-output-hk/cardano-wallet/pull/264#discussion_r252371660) but, this was really about a way of "optimizing" this in case there is any need for optimization.

Could we please first get to something workable before trying to shove in any sort of optimization :pray: ? There's no point in optimizing something we can't analyze and measure first.

2019-02-07 16:00 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOurs _ s@(Map.null -> True) = (Nothing, s)
yes true, I'll remove these from both IsOurs instances

2019-02-08 03:24 UTC, parsonsmatt approved these changes

2019-02-08 03:24 UTC, parsonsmatt commented on src/Cardano/Wallet/Kernel/BListener.hs
> +-- (e.g. writing into the acid-state DB log) by skipping such block application).
This should be in the Haddock comment

2019-02-08 10:31 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/BListener.hs
> -                             <> "a different number of elements than the input ones."
@uroboros This has been left unanswered but, what am I missing :thinking: ?

2019-02-08 10:43 UTC, uroboros reviewed
@KtorZ regarding your question about removing the invariant - I see my comment was "Pending" ;( - here it is "because I'm using a NonEmpty list now, so there's no "impossible" anymore. The error msg is incorrect though, it was failing when there was more than one prefilter result (not "a different number of elements")"

2019-02-08 10:43 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +    isOurs :: Core.Address -> Map k v -> (Maybe HdAddress, Map k v)
this is an important change because we need to be able to recognise empty prefiltering context. You'll see that at the entry points of prefiltering, without such a mechanism, in the case of empty prefiltering context, we would have to trivial call to isOurs for every single output address in a block of transactions.

2019-02-08 11:55 UTC, KtorZ commented
I believe the invariant error was _right_, and was there to enforce that after prefiltering a singleton block, we get back a singleton result. 
Note that using a `NonEmpty` list doesn't quite solve the issue because we are now swallowing the failing pattern match because of:

```
     nonEmpty <$> prefilterBlocks_ bs foreigns hdRnds 
```

If, given a non empty list of blocks, prefilterBlocks was to return an empty list (or, as the original invariant indicated, a different number of blocks), then this is now appears as if there were no credentials at all and we would discard this result, without even knowing that something has happened. 

I think the real question here is why do we use a version of `prefilterBlocks` that relies on a list of blocks, where we do know that we are only passing around a single block.

https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/BListener.hs#L210

I agree there's no need for this invariant, the fix however isn't going in the right direction. Rather, make `prefilterBlock` singular and have it take a single block and then later, in

https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/BListener.hs#L312

fallback to a `forM` or` mapM` of that function -- that's what the current implementation does anyway. 

Moreover, this new function of yours `prefilterBlocks_` does a fair job at focusing only on the prefiltering part, leaving to the caller the freedom of getting the corresponding credentials (and not doing this in `prefilterBlocks` itself). It's nice to keep function doing one-and-one thing only. 



PS: stylish-haskell isn't happy :/

2019-02-08 14:55 UTC, KtorZ approved these changes

2019-02-08 14:57 UTC, uroboros commented on src/Cardano/Wallet/Kernel/BListener.hs
> +prefilterBlock
@KtorZ when I introduce EO prefiltering, we must cater for both EO + FO wallets being present. That means this function should return `IO (NonEmpty PrefilterResult)` because there might be multiple results (one for each wallet class). Alternatively we could defined <> for PrefilterResult, but I am not sure enough yet of the impact of such a change.

2019-02-08 14:57 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/BListener.hs
> +    return (foreigns, hdFOs)
Note that we are changing the original behavior here and getting rid of one of the "optimizations" introduced as part of a fix during the 1.4.x QA phase. We use to return `Nothing` when there was no credentials / wallet to deal with, in order to skip prefiltering completely after.

So, the `Maybe` is gone, but there's no additional check at the caller site here to verify whether the second `Map` actually contains some credentials. It shouldn't matter much in practice, but let's keep that in mind for testing.

2019-02-08 15:04 UTC, uroboros commented on src/Cardano/Wallet/Kernel/BListener.hs
> +    return (foreigns, hdFOs)
ok, I'll make sure to skip prefiltering if there are no credentials (this becomes even more important when I add the EO wallet type here)

2019-02-08 15:13 UTC, uroboros commented on src/Cardano/Wallet/Kernel/BListener.hs
> +    return (foreigns, hdFOs)
(on second thought, I'll have to return that Maybe PrefResult)

2019-02-11 11:59 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
>          Nothing     -> error "mkAddressPool: maximum number of addresses reached."
We decided to keep `error` here, right? I mean, is it appropriate solution here?

2019-02-11 12:35 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
>          Nothing     -> error "mkAddressPool: maximum number of addresses reached."
I'll make that part of ErrAddressPoolInvalid instead...

2019-02-11 12:35 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
>          Nothing     -> error "mkAddressPool: maximum number of addresses reached."
(will remove error call)

2019-02-11 13:24 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
>          Nothing     -> error "mkAddressPool: maximum number of addresses reached."
@denisshevchenko on further thought, this behaviour is correct: this function will be deferred to during prefiltering (when an address pool gets extended). In that case it will have to fail hard if address generation fails. There are some other hard fails that occur during SwitchToFork and Appyblock

2019-02-12 07:54 UTC, rvl approved these changes
Looks good as far as I can tell. I only have questions or stylistic suggestions that you are free to ignore.

2019-02-12 07:54 UTC, rvl commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +mkAddressPool mkAddress accPK gap
After adding `mkAddressPoolExisting`, should `mkAddressPool` be renamed to `mkAddressPoolFullyOwned`?

2019-02-12 07:54 UTC, rvl commented on src/Cardano/Wallet/Kernel/BListener.hs
> +    -> IO ( Map HdAccountId (Set TxIn)
Would it aid readability if the return value of `prefilterContext` were packed into a little local data type?

2019-02-12 07:54 UTC, rvl commented on src/Cardano/Wallet/Kernel/Restore.hs
> +        Just rb -> flip evalStateT (M.singleton rootId esk) $ do
Could this be shortened to `M.fromList [creds]`? Same goes for `getWalletInitInfo`.

2019-02-12 07:54 UTC, rvl commented on src/Cardano/Wallet/Kernel/Read.hs
> +getEosPools db mkAddress
Would this function need any logging to aid users if the exceptional cases occurred?

2019-02-12 07:54 UTC, rvl commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +instance IsOurs (Map HdRootId Core.EncryptedSecretKey) where
Does this change of type affect the DB schema at all? I'm thinking probably not.

2019-02-12 08:37 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +mkAddressPool mkAddress accPK gap
both of these functions are only relevant to EO wallet AddressPools - but I agree these names don't sit well together. mkAddressPool is not being used yet (coming soon), I'll look for better names when I use it.

2019-02-12 08:38 UTC, uroboros commented on src/Cardano/Wallet/Kernel/BListener.hs
> +    -> IO ( Map HdAccountId (Set TxIn)
I was tempted by that - but then this would be the only use case.

2019-02-12 08:39 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Restore.hs
> +        Just rb -> flip evalStateT (M.singleton rootId esk) $ do
here I think `M.singleton rootId esk` makes it more explicit that we are dealing with one wallet only

2019-02-12 08:41 UTC, uroboros commented on src/Cardano/Wallet/Kernel/Read.hs
> +getEosPools db mkAddress
that does need more work yes - since I'll be touching this function in the next 2 PRs I'll carry that over to later

2019-02-12 08:41 UTC, uroboros commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +instance IsOurs (Map HdRootId Core.EncryptedSecretKey) where
IsOurs is used for prefiltering and does land in the DB in any explicit way

2019-02-12 09:40 UTC, akegalj approved these changes
LGTM

Some logic was harder to grasp for me as I need some concepts to soak in.

I wonder is `test/unit/Util/Prefiltering.hs` covering all changes introduced here or do we need to add more tests?

2019-02-12 09:40 UTC, akegalj commented on src/Cardano/Wallet/Kernel/Addresses.hs
> +        -> Map HdRootId EncryptedSecretKey
:+1:

2019-02-12 09:40 UTC, akegalj commented on src/Cardano/Wallet/Kernel/DB/HdWallet.hs
> +instance IsOurs (Map HdRootId Core.EncryptedSecretKey) where
I don't think we are storing this info in this format

2019-02-12 09:40 UTC, akegalj commented on src/Cardano/Wallet/Kernel/Read.hs
> +            (Just (Left err))          -> error (sformat build err)
we have decided to fatal fail here - are we sure there is no way to recover from `GetAddressPoolGapError` ? Maybe there is no need though

2019-02-12 09:43 UTC, merged