Check for Read, Delete and Update operations, for all wallets.
input-output-hk/cardano-wallet-legacy pull request #337
Opened 2019-02-12 19:17 UTC by denisshevchenko

<p align="right">#336</p>

# Overview

- [ ] I have ...

# Comments

2019-02-13 05:22 UTC, uroboros requested changes

2019-02-13 05:22 UTC, uroboros commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    case addressPoolGapByRootId rootId db of
We are using `addressPoolGapByRootId` for asking "is EO wallet". I think it's worth making it more explicit with a wrapper `isEOWallet :: DB -> HdRootId -> Bool`

2019-02-13 05:22 UTC, uroboros commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    case addressPoolGapByRootId rootId db' of
if you use `eosAccountsByRootId` here instead of `addressPoolGapByRootId`, this function will simplify quite a bit

2019-02-13 05:22 UTC, uroboros commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    case addressPoolGapByRootId rootId db of
(we might as well add an isFOWallet too?)

2019-02-13 07:09 UTC, rvl reviewed
1. I think we could reduce the repetition and make it clearer.

2. I agree with @uroboros, but rather than `isEOWallet` and `isFOWallet` we could have something like:

```
data WalletOwnership
    = WalletFullyOwned
    | WalletExternallyOwned
    deriving (Show, Eq)

getWalletOwnership :: HD.HdRootId -> Kernel.PassiveWallet -> IO WalletOwnership
getWalletOwnership rootId = fmap ownership . Kernel.getWalletSnapshot
    where
        ownership db = case addressPoolGapByRootId rootId db of
                           Right _ -> WalletExternallyOwned
                           Left _ -> WalletFullyOwned
```

3. Is `HD.UnknownHdRoot` the right exception, or should there be another one added for the case where the action is not applicable?

2019-02-13 08:45 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    case addressPoolGapByRootId rootId db of
Agree. I'll do it.

2019-02-14 09:10 UTC, uroboros requested changes
mostly LGTM - just one issue with `updateEosWallet`

2019-02-14 09:10 UTC, uroboros commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    db' <- liftIO $ Kernel.getWalletSnapshot wallet
As it stands, we're repeating logic that is captured by `eosAccountsByRootId`.
If you use that function instead of `getWalletOwnership` you'll get
* accountIds, no need to read them again
* checks for `GetEosWalletErrorNoAccounts` and `GetEosWalletErrorWrongAccounts` are built in

2019-02-14 09:10 UTC, uroboros commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    case getWalletOwnership rootId db of
A (debatable) suggestion...

We can simplify these calls to `getWalletOwnership` with a helper function, e.g. 

`ensureOwnership :: WalletOwnership -> (HdRootId -> e) -> ...`

and use it like this:

_ <- ensureOwnership WalletFullyOwned (UpdateWalletError . HD.UnknownHdRoot)
-- from here on we can assume correct ownership...

2019-02-15 05:28 UTC, akegalj commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    case getWalletOwnership rootId db of
I like the proposal but underlying code would not change much. We would still have to do pattern on `case` expression - only some bits of the code would be rearanged slightly.

But its up to you - I am fine with both solutions

2019-02-15 05:28 UTC, akegalj commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    db' <- liftIO $ Kernel.getWalletSnapshot wallet
@denisshevchenko what are your thoughts on this?

2019-02-15 09:18 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    db' <- liftIO $ Kernel.getWalletSnapshot wallet
Yes, good idea. I'll use that function.

2019-02-15 10:53 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +    db' <- liftIO $ Kernel.getWalletSnapshot wallet
Done.

2019-02-15 12:08 UTC, uroboros approved these changes
LGTM!

2019-02-15 16:02 UTC, akegalj approved these changes

2019-02-15 16:02 UTC, merged