WALLET_DETAILS integration tests
input-output-hk/cardano-wallet-legacy pull request #344
Opened 2019-02-15 16:28 UTC by piotr-iohk

<p align="right">#</p>

# Overview

- [ ] I have added tests for WALLET_DETAILS capability (https://docs.google.com/spreadsheets/d/1ztF2PnnrMnkAxrhdq3LUbP1KazxcxuMrbiObTs1CuTk)

# Comments

2019-02-18 13:22 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        --     ]
It seems I cannot get the desired amount on the destination wallet, even if on the `Client.postTransaction` request before I am waiting for the transaction status to be `expectTxStatusEventually [Persisted]`... Is there any other way I can make sure the amount from the transaction reached the destination? In particular I'd like to use endpoint `Client.getWallet` to verify the amount is there.

2019-02-18 13:35 UTC, KtorZ requested changes

2019-02-18 13:35 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    , eosCreatedAt
This defy a bit the purpose of using lenses here :sweat_smile:  ... I believe we can define a `Lens s WalletTimestamp` quite easily, where `s` can be either a `Wallet` or an `EosWallet`

2019-02-18 13:35 UTC, KtorZ commented on test/integration/Test/Integration/Framework/DSL.hs
> +    , eosCreatedAt
Note, this probably conflicts with the `spendingPasswordLastUpdate` because both timestamps have a similar type. Alright, we'll need to give it some thoughts.

2019-02-18 13:35 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            ]
Fee are only constant here because we don't have any activity on the local cluster beside this very scenario. In practice, this isn't guaranteed at all, and that's why it's called "estimate fee". They may likely diverge from the actual ones especially on wallets with many UTxOs where inputs are selected randomly. You may end up with slightly different fees in practice.

Ideally, we would verify that the balance is less than before by at least, the amount of the transaction + the minimal fee. But that's pretty much all.

2019-02-18 13:35 UTC, KtorZ commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        --     ]
So. The addresses present in the fixture aren't addresses of the underlying wallet. They are just a bunch of random addresses one can use to make payment too, but they aren't tracked by the wallet described in the fixture at all. Hence you not getting the wallet to be updated with the amount; funds are actually sent to... another random wallet.

If you want to get send to a particular address of that fixture wallet, use `customDistribution` and provide an account for that destination wallet instead :+1:

2019-02-19 08:54 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +            ]
>Fee are only constant here because we don't have any activity on the local cluster beside this very scenario.

Given the circumstances you mention ^, do we want to change the scenario to what you propose or leave it as is?

If we'd like to change it to:
>we would verify that the balance is less than before by at least, the amount of the transaction + the minimal fee. But that's pretty much all.

then how do we calculate the minimal fee?

2019-02-19 08:55 UTC, piotr-iohk commented on test/integration/Test/Integration/Scenario/Wallets.hs
> +        --     ]
ah, ok :+1:

2019-02-19 13:06 UTC, piotr-iohk commented on test/integration/Test/Integration/Framework/DSL.hs
> +    , eosCreatedAt
If we are after having a lens with the name `createdAt` that works for both `Wallet` and `EosWallet` this is something I came up with:

```haskell
createdAt :: HasPosition 6 s s WalletTimestamp WalletTimestamp => Lens' s WalletTimestamp
createdAt = position @6
```
as it turns out that `walCreatedAt` and `eoswalCreatedAt` are both on the 6th position in their respective datatypes.

We could have that istead of:

```haskell
createdAt :: Lens' Wallet WalletTimestamp
createdAt = field @"walCreatedAt"

eosCreatedAt :: Lens' EosWallet WalletTimestamp
eosCreatedAt = field @"eoswalCreatedAt" 
```

I imagine that this is probably not the nicest approach but... well, do let know :)

2019-02-21 09:59 UTC, piotr-iohk commented
@KtorZ I have pushed the changes requested. I had two questions about:
 - `createdAt`_implementation_ using `HasPosition` (pushed this)
 - calculating minimal fee if we want to verify balance of the wallet after outgoing transaction differently

However If the tests are good as they are i think it might be merged...

2019-02-21 10:08 UTC, KtorZ approved these changes

2019-02-21 10:09 UTC, merged