API V1 types: EOS-wallet related types logging improving.
input-output-hk/cardano-wallet-legacy pull request #352
Opened 2019-02-20 08:22 UTC by denisshevchenko

<p align="right">#315</p>

# Overview

- [ ] I have ...

# Comments

2019-02-20 08:30 UTC, denisshevchenko commented
Examples.

`EosWallet`:

```
EOS (externally-owned sequential) wallet
  wallet id: J7rQqaLLHBFPrgJXwpktaMB1B1kQBXAyc2uRSfRPzNVGiv6TdxBzkPNBUWysZZZdhFG9gRy3sQFfX5wfpLbi4XTFGFxTg
  name: My EOS-wallet
  balance: 1104330362855056 coin(s)
  address pool gap: 84
  assurance level: strict
  created at: 1191686829598181
```

---

`NewEosWallet`:

```
Request for new EOS wallet
  name: My EOS-wallet
  address pool gap is undefined (default value 20 will be used)
  assurance level: normal
  accounts:
  - account public key: pub:b7732ec4, account ix: 3965755267
  - account public key: pub:1762b3cb, account ix: 3195482834
  - account public key: pub:b30d4f07, account ix: 3964313652
  - account public key: pub:30329f70, account ix: 2289830138
  - account public key: pub:b951bb70, account ix: 3797983371
  - account public key: pub:7cd01c19, account ix: 4212473129
  - account public key: pub:f5e60727, account ix: 3249079988
```

or:

```
Request for new EOS wallet
  name: My EOS-wallet
  address pool gap: 52
  assurance level: strict
  accounts:
  - account public key: pub:055c7ccb, account ix: 3192540224
  - account public key: pub:2623aacf, account ix: 3257216011
  - account public key: pub:eb787acf, account ix: 3476420452
```

---

`UpdateEosWallet`:

```
Update for EOS wallet
  name: My EosWallet
  assurance level: normal
  address pool gap: 44
```

2019-02-20 10:21 UTC, akegalj requested changes
There are some privacy issues I believe with this PR as we are dropping safe/private logging

2019-02-20 10:21 UTC, akegalj commented on src/Cardano/Wallet/API/V1/Types.hs
> +    % "\n  name: " % build
don't we leak info this way? I guess this would be good for development purpose but we don't want to leak id, name, balance in production logs.

I guess that's the whole idea behind `buildSafe` - to give us ability to guard and hide those details in production setting

2019-02-20 10:21 UTC, akegalj commented on src/Cardano/Wallet/API/V1/Types.hs
> +        % "\n  accounts:\n" % buildIndent 2 (buildList build)
wallet name should be safe and not printed out in production - this leaks info

2019-02-20 10:21 UTC, akegalj commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +instance {-# OVERLAPPING #-} Buildable (Maybe AddressPoolGap) where
We usually don't like overlapping instances but I think this is ok use case

2019-02-20 10:50 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +    % "\n  name: " % build
> but we don't want to leak id, name, balance in production logs.

What's the problem with wallet id and wallet name in production logs??

2019-02-20 10:52 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +        % "\n  accounts:\n" % buildIndent 2 (buildList build)
Why? It's just an arbitrary human-readable string, for example "My favorite cat is Jack". :-)

2019-02-20 11:54 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +    % "\n  name: " % build
@akegalj Ok, now balance is hidden via `buildSafe`.

2019-02-20 13:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +        % "\n  accounts:\n" % buildIndent 2 (buildList build)
Agreed with @denisshevchenko on that. The name is just a metadata and is actually truly helpful to have in logs since that's what user use when they refer to their wallets.

I agree about hiding the balance though. That's is not something that is easily available from the blockchain since, in order to keep track of a wallet balance, one would require the private key (or at least, the public key). There's also a very minor "privacy" issue with the showing the complete account key. Note however that, those concerns are rather delusional since the database is anyway freely available unencrypted. So, all those pieces of information are already there on disk, and can be read at any time by any party having access to the files. 

Let's see what Charles Morgan and David think about this. I've already started a conversation with them on topic in order to know where to draw the line of privacy.

2019-02-20 13:42 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +        % "\n  accounts:\n" % buildIndent 2 (buildList build)
> I agree about hiding the balance though.

It is hidden already, via `buildSafe`.

2019-02-21 08:40 UTC, akegalj commented on src/Cardano/Wallet/API/V1/Types.hs
> +        % "\n  accounts:\n" % buildIndent 2 (buildList build)
> Why? It's just an arbitrary human-readable string, for example "My favorite cat is Jack".

heh - it might be "stash for drugs" as well. If we are going to show this I believe we should have a note somewhere in our privacy leter that user is accepting about this to communicate that name/id/... will be listed in logs - so that user is aware of it and doesn't sue us or smth

2019-02-21 09:33 UTC, akegalj approved these changes
After discussion with rest of the team conclusion is that it is ok to log these details as Daedalus is already logging name/balance . Even then, we don't upload any logs automatically but user has to do it manually

2019-02-21 09:33 UTC, akegalj commented on src/Cardano/Wallet/API/V1/Types.hs
> +    % "\n  balance: " % buildSafe sl
although it turns out in the last discussion we had with guys that it is ok to show balance as well as daedalus is dumping wallet balances to the logs

2019-02-21 09:33 UTC, akegalj commented on src/Cardano/Wallet/API/V1/Types.hs
> +        % "\n  accounts:\n" % buildIndent 2 (buildList build)
We concluded in the slack discussion that it is ok to show name in logs as daedalus is already doing this and we are not pulling logs automatically - but user has to manually upload them to us.

2019-02-21 09:33 UTC, merged