BIP-44 A. Review & Extend Existing API & Handlers
input-output-hk/cardano-wallet-legacy pull request #57
Opened 2018-11-13 14:16 UTC by denisshevchenko

Review & Extend Existing API & Handlers (3 points)

1. The API must support 'Create' operation on E.O.S Wallets.
2. Address Pool Gap may be configurable per E.O.S Wallets at the API-level.

2018-11-15 12:41 UTC, KtorZ requested changes

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +            & type_ .~ SwaggerString
NOTE:  Swagger also supports a `format` type which is handy to specify encoding formats like `base58` :+1:

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +createHdExternalWallet :: EosHdRoot
Should we also rename to "createEosHdWallet" ?

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +        numOfAccounts = fromIntegral $ length accountsPKs
This isn't true. In the case of EOS wallets, we just _don't know_ the account indexes. And in theory, we don't need to know them since we won't be deriving new accounts.

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +    , eosAccountUpdateNew   :: !AccountUpdateNew
"when we need to create the account from scratch"

I suppose this won't happen with EOS accounts ?

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +eosAccountUpdateCreate :: HdAccountId -> AccountUpdateNew -> PublicKey -> EosHdAccount
So yeah, EOS wallets' accounts are really _just_ public keys. There's no index or id whatsoever.

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +    return res
hlint not happy here :upside_down_face: 

```hs 
do
  a <- io 
  return a

-- vs

do
  io

```

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/EosHdWallet.hs
> +    } deriving (Eq, Show)
:+1:

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/EosHdWallet.hs
> +      _eosHdAccountId            :: !HdAccountId
To be removed, cf comments above.

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/EosHdWallet.hs
> +    , _eosHdAccountAutoPkCounter :: !AutoIncrementKey
Not sure what this is :thinking: ?

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +                       -> [PublicKey]
Same as previous comment. we may want to rename this function as well :+1:

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +    -- key as a base for wallet's 'HdRoot'.
Hopla! This should come from the API or be derived from it. A `RootId` is merely an `Address` derived from the wallet root public key. I think that's a fair thing to ask from the API (as it was already the case I believe?)

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +                then throwError $ CreateExternalWalletInvalidAccountPK $ problems !! 0
Let's not throw here but leverage the `ExceptT` monad and  return a "pure" failure.

2018-11-15 12:41 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +                          }
Just  a minor styling advice: prefer the example below than the above. Variable-length indentation is a pain and creates unnecessary conflicts with git; try to avoid it at most. I know it's in a lot of place in the current codebase, but let's not introduce new ones :) 

```hs
mkExternalWallet 
  :: Text
  -> [PublicKey]
  -> Word
  -> V1.AssuranceLevel
  -> EosHD.EosHdRoot
  -> V1.ExternalWallet
mkExternalWallet v1WalletName accountsPKs addressPoolGap v1AssuranceLevel eosHdRoot =
    V1.ExternalWallet 
      { ewalId             = walletId
      , ewalName           = v1WalletName
      , ewalAccountsPKs    = accountsPKs
      , ewalAddressPoolGap = addressPoolGap
      , ewalBalance        = V1 (mkCoin 0)
      , ewalAssuranceLevel = v1AssuranceLevel
      }
```

2018-11-20 16:25 UTC, KtorZ requested changes

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
>          )
I believe this schema is wrong. This is parsed and serialized a JSON `String` and not an object, right ?

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
>          )
Same as above.

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
>      } deriving (Eq, Generic, Ord, Show)
Wondering: what's the need for a `newtype` here? Current `Address` are already serialized from and to Base58 JSON Strings :thinking:

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    , neweoswalAddressPoolGap :: !(Maybe Word)
NOTE for later: We probably want something much smaller than `word` here.

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +            & ("accountsPKs"    --^ "External wallet's accounts public keys.")
let's go for `publicKeys`, don't you think? I think it's clearer at the api-level, or at the very least: `accountPublicKeys` to avoid acronyms.

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +exampleEosWalletId = EosWalletId "c2cc10e1-57d6-4b6f-9899-38d972112d8c"
Let's use the `Example` class for that :upside_down_face:

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +    }
Out-of-scope for this PR / story. But, okay (don't remove it know. We'll refine if needed when time comes) :sweat_smile:

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/AcidState.hs
> +        ((eosAccountUpdatePK, ) <$> eosAccountUpdate)
Out-of-scope for this PR / story. But, okay (don't remove it know. We'll refine if needed when time comes) :sweat_smile:

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/EosHdWallet.hs
> +    arbitrary = EosHdRootId <$> pure (fromJust $ Uuid.fromText "550e8400-e29b-41d4-a716-446655440000")
`UUID` implements the `Random` type-class, we can derive `arbitrary` from it using [`chooseAny`](https://hackage.haskell.org/package/QuickCheck-2.12.6.1/docs/Test-QuickCheck-Gen.html#v:chooseAny)

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    deriving (Show, Eq, Ord, Generic)
Why isn't this a `UUID` instead of `Text` :thinking:  ?

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/EosHdWallet/Create.hs
> +    }
Not sure to get the use for those functions :thinking: ? They are just `EosHdRoot` and `EosHdAccount` ...

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/DB/EosHdWallet.hs
> +    deriving (Eq, Ord, Show)
_[should fix]_

I'd see value in a `newEosHdRootId = EosHdRootId <$> randomIO :: IO EosHdRootId` to avoid bubbling the `uuid` and `random` package everywhere outside here.

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +            return (Right eosHdRoot)
What about:

```hs
return $ case res of
    Left e@(EosHD.CreateEosHdRootExists _) ->
        Left $ CreateEosWalletFailed e
    Right _ -> 
      Right newEosRoot
```

:sweat_smile: ?

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer.hs
> +    CreateEosWalletNoAccountsPKs
Not sure what this is for, but I don't think it's a requirement to have non-empty list of accounts :thinking: ? Should work with an empty list.

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +        then ExceptT $ return $ Left CreateEosWalletNoAccountsPKs
cf comment above :+1:

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +                then ExceptT $ return $ Left $ CreateEosWalletInvalidAccountPK $ problems !! 0
All this should happen at the API-level I believe; It would suffice to have more constrained API types and have this parsing done in the JSON serializers / deserializers.

2018-11-20 16:25 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +            }
No need for this indirection :+1:

2018-11-20 17:15 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +    , neweoswalAddressPoolGap :: !(Maybe Word)
`Word8`?

2018-11-20 17:51 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    , neweoswalAddressPoolGap :: !(Maybe Word)
or "newtype AddressPoolGap" :sweat_smile: ... even a `Word8` is too big I believe.

2018-11-21 11:40 UTC, KtorZ requested changes
Getting there :stuck_out_tongue: 
Still some points that must be changed, and some that I think can be tackled in a new PR!

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    arbitrary = example
_[must fix]_

Nope! That's, at best, the other way around. 

- Arbitrary = Generators we use for testing.
- Example = Human-friendly values we display in the documentation

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    { neweoswalAccountsPublicKeys :: ![PublicKeyAsBase58]
_[should fix]_

Can we shove `PublicKey` directly here? Why do we need this intermediate type ? (Or at least, have a `PublicKey` inside a `PublicKeyAsBase58` instead of a raw `Text`.

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    , eoswalAccountsPublicKeys :: ![PublicKey]
_[may fix]_

I am thinking out-loud here but, do we actually need this at all :thinking: ? I mean.. Having an endpoint `/wallets/{id}/accounts`, we already have a way to get this list of public keys :) ... So in the end, to make the API representation a bit more orthogonal, we could just remove public keys completely from the representation and only keep those in our internal wallet layer type. 

What do you think ?

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    example = EosWalletId <$> pure (fromJust . Uuid.fromText $ "c2cc10e1-57d6-4b6f-9899-38d972112d8c")
_[may fix]_

Side-note: that's one of those cases where I think `read "c2cc10e1-57d6-4b6f-9899-38d972112d8c"` is totally fine :)

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +    return $ case either Left (const (Right newEosRoot)) res of
_[may fix]_ 

:sweat_smile:  my point wasn't much about the `return $` (I just noticed ...) but more about the unecessary `either Left (const (Right ...))`, this is unnecessary complicated as we are truly just doing `case res of`

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer.hs
>      show = formatToString build
_[must fix]_ 

Arg! No! Didn't catch that before but, please no custom `Show` instances :(, those should be derived only and always respect `show . read = id`

If there's any other type doing so, may you please open a ticket to remove them all :)

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer.hs
>      show = formatToString build
_[must fix]_

Cf above.

2018-11-21 11:40 UTC, KtorZ commented on src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
> +        else do
_[should fix]_ 

Reflecting on the comment above about having a more precise type for public keys in `NewEosWallet`. This should be caught earlier. And as a rule of thumb, we can eliminate a whole class of errors by having better types. There's no need to handle conversions from text to public keys if we directly manipulate public keys :smile:

2018-11-21 19:08 UTC, denisshevchenko commented on src/Cardano/Wallet/WalletLayer.hs
>      show = formatToString build
> If there's any other type doing so, may you please open a ticket to remove them all :)

Yes, there's a LOT of other types doing so..

2018-11-22 07:41 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
>          )
Type `PublicKeyAsBase58` will be removed in the next PRs.

2018-11-22 08:44 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
>      arbitrary = oneof []
_[should fix]_

Just noticing now but not sure that this will play with Quickcheck when generating stuff :sweat_smile:

2018-11-22 08:47 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Wallets.hs
>      arbitrary = oneof []
I just took it from:

```
instance Arbitrary CreateWalletError where
    arbitrary = oneof []

```

:-)

2018-11-22 08:47 UTC, KtorZ approved these changes
LGTM :+1:

As a reminder:

_should fix_

- [ ] arbitrary instance of `CreateEosWalletError` -> `oneof []` (this throws as runtime :upside_down_face: )
- [ ] provide a smart constructor for generating new `EosRootId`
- [ ] define a tailored type for `addressPoolGap`
- [ ] clean-up unused types and constructors (related to `PublicKeyAsBase58` mostly)

2018-11-22 08:48 UTC, merged

2018-11-22 08:49 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
>      arbitrary = oneof []
I know :upside_down_face:  .... 

![image](https://user-images.githubusercontent.com/5680256/48891511-d6430e00-ee3b-11e8-860f-eacfd2bcad77.png)

Guess we have never used those `Arbitrary` instances ...