[BIP44-33] AddressPool - core types and algorithm to support address …
input-output-hk/cardano-wallet-legacy pull request #73
Opened 2018-11-22 09:22 UTC by uroboros

…discovery for EOS/FOS wallets

# Linked Issue

https://github.com/input-output-hk/cardano-wallet/issues/33

# Comments

First draft of AddressPool module, sans any tests.

2018-11-23 15:08 UTC, KtorZ requested changes
- Let's not even mention FOS wallets at this stage
- We ought to provide a "dead simple" API for this module and have the complexity lives inside it

Haven't much reviewed the algorithm so-to-speak as I think the various comment will provoke some important refactoring :/ 
Also, make sure to align with @denisshevchenko on the `AddressPoolGap` type.

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +       ) where
so
many 
new
lines

:smile:

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +type AddressPoolGap = Word32
_may fix_

`Word32` sounds like a lot. This has some overlap with #85; so I'd suggest to align with @denisshevchenko and either conflate the two modules into one, or have this one import the AddressPoolGap type.

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +import           Cardano.Wallet.Kernel.DB.HdWallet(HdAddressIx (..))
_must fix_

This one doesn't belong here I believe.

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +    = (f fromIx) NE.:| (map f [fromIx + 1 .. fromIx + range - 1])
_may fix_ 

No need for qualified import here, `:|` is common enough to be used as a operator.

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +    }
_must fix_

Let's not bother about FOS wallet now and proceed in steps. For now, we only consider case where we ignore relationship accounts have to each others and we only build from a set of account public keys.

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +             -> [(account, HdAddressIx)]
_must fix_

This looks a lot complicated for an exposed function. One of the goal we want to achieve by making an isolated module is to provide some easy handles on an opaque type such that, it's easy for users of this module to achieve what they want. 

```hs
addrInPool 
  :: AddressPool account address
  -> address
  -> (AddressPool account address, Maybe (account, AddressIdx))
addrInPool ... =
```

That's all we should need, right ?

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +         AccountPoolAmendment (..)
_must fix_

We expose too many things from this module. The point of making this an isolated module is to encapsulate the complexity and implementation details inside the module and make sure they don't get out! 
Underneath it all, the API boils down to this:

```hs
module 
  ( AddressPool
  , initAddressPool
  , addrInPool -- cf comment below
  ) where
```

We may provide some extra "debugging" / testing helpers like "totalPoolSize" to help us write properties about those. But, conceptually, I believe we don't need to expose more than that, don't we?

2018-11-23 15:08 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/HdSeq.hs
> +data AccountPool account address = AccountPool {
_may fix_ 

What above shoving in there the `Ord` and `Eq` instances for `account` and `address` ?

2018-11-27 17:29 UTC, denisshevchenko commented
Closed, because simplified version is here: https://github.com/input-output-hk/cardano-wallet/pull/118

2018-11-27 17:29 UTC, closed without merging