BIP-44 A. New type AddressPoolGap.
input-output-hk/cardano-wallet-legacy pull request #85
Opened 2018-11-22 14:04 UTC by denisshevchenko

# Linked Issue

<Put here a reference to the issue this PR relates to and which requirements it tackles>

https://github.com/input-output-hk/cardano-wallet/issues/28

### Acceptance criteria:

1. - [ ] Address pool gap is represented as a new type.

# Comments

<Additional comments or screenshots to attach>

¯\\\_(ツ)\_/¯

# Checklist

- [ ] I've kept this PR simple, on-the-spot, free of cosmetic changes.
- [ ] I have reviewed my commit messages and history.
- [ ] I've assigned a reviewer.
- [ ] I acknowledge my changes may require an update in the wiki.
- [ ] I have added a reference to this PR to the corresponding issue.

---

- [ ] I've checked the checklist

2018-11-22 17:06 UTC, KtorZ requested changes

2018-11-22 17:06 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +instance ToJSONKey AddressPoolGap
:thinking: What's that for ?

2018-11-22 17:06 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +
_[must fix]_

I think we need a smart constructor here. Let's enforce a gap between 10 and 100 (completely arbitrary, but we can change later). 
Then, let's use that smart constructor to define the Arbitrary and HttpApiData instances.

2018-11-22 17:06 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +                  -> Word8
_[must fix]_

Why not `AddressPoolGap` here ?

2018-11-22 17:15 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +                  -> Word8
Because `AddressPoolGap` is defined in `API/V1/Types`. I shouldn't use types from wallet layer in the `Kernel`, right? Or I'm wrong?

2018-11-22 17:16 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +                  -> Word8
You're right. But, what about defining `AddressPoolGap` in the kernel then :trollface:  ?

2018-11-22 17:18 UTC, denisshevchenko commented on src/Cardano/Wallet/API/V1/Types.hs
> +instance ToJSONKey AddressPoolGap
I don't know, just copied it... :-) Removed.

2018-11-22 17:25 UTC, denisshevchenko commented on src/Cardano/Wallet/Kernel/Wallets.hs
> +                  -> Word8
Hm... I didn't thought about it. :-) Thanks, I'll do it.

2018-11-23 09:44 UTC, uroboros reviewed
looks good! I have nothing to add

2018-11-23 15:09 UTC, KtorZ requested changes
Looks good, only a concern about the Error type here!

2018-11-23 15:09 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +type Gap = Word8
_should fix_

I think that's overkill here ^^"

2018-11-23 15:09 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +    maxBound = AddressPoolGap 100
:+1:

2018-11-23 15:09 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +    deriving (Eq, Show)
_must fix_

This suggests a monolithic `AddressPoolGapError` which will bite us as some point. I'd rather go for something more specific to the use-case with also, a constructor giving more details about what the error actually is.

```hs
newtype MkAddressPoolGapError = GapOutOfRange Word8
    deriving (Eq, Show)
```

2018-11-23 15:09 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +    deriving (Eq, Show)
I know a guy who wrote something interesting on the topic, perhaps you know him too :stuck_out_tongue: 

https://www.parsonsmatt.org/2018/11/03/trouble_with_typed_errors.html

2018-11-23 15:09 UTC, KtorZ commented on src/Cardano/Wallet/Kernel/AddressPoolGap.hs
> +    | otherwise = Left $ AddressPoolGapError gap
Sweet :)

2018-11-23 15:09 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +    toQueryParam gap = sformat build gap
_must fix_

What about moving that into the AddressPoolGap module to avoid orphan instances here :sweat_smile:  ?

2018-11-23 16:11 UTC, KtorZ commented on src/Cardano/Wallet/API/V1/Types.hs
> +deriveJSON Aeson.defaultOptions ''AddressPoolGap
_must fix_

Oversight here: this generates orphan instances, should be in the address gap module :+1:

2018-11-23 16:55 UTC, KtorZ approved these changes

2018-11-23 16:55 UTC, merged